In [1]:
import pandas as pd
import numpy as np

#### Get Canucks Attendance

In [2]:
attendance = pd.read_csv('../data/canucks/canucks_201819_schedule.csv')

In [3]:
attendance

,GP,Date,Unnamed: 2,Opponent,GF,GA,Unnamed: 6,Unnamed: 7,W,L,OL,Streak,Att.,LOG,Notes
0,1,2018-10-03,NaN,Calgary Flames,5,2,W,NaN,1,0,0,W 1,18870,2:31,NaN
1,2,2018-10-06,@,Calgary Flames,4,7,L,NaN,1,1,0,L 1,18688,2:39,NaN
2,3,2018-10-09,@,Carolina Hurricanes,3,5,L,NaN,1,2,0,L 2,11932,2:35,NaN
3,4,2018-10-11,@,Tampa Bay Lightning,4,1,W,NaN,2,2,0,W 1,19092,2:23,NaN
4,5,2018-10-13,@,Florida Panthers,3,2,W,NaN,3,2,0,W 2,11953,2:32,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,78,2019-03-28,NaN,Los Angeles Kings,3,2,W,SO,33,35,10,W 1,18524,2:38,NaN
78,79,2019-03-30,NaN,Dallas Stars,3,2,W,SO,34,35,10,W 2,18663,2:42,NaN
79,80,2019-04-02,NaN,San Jose Sharks,4,2,W,NaN,35,35,10,W 3,18524,2:22,NaN
80,81,2019-04-04,@,Nashville Predators,2,3,L,NaN,35,36,10,L 1,17669,2:24,NaN
81,82,2019-04-06,@,St. Louis Blues,2,3,L,SO,35,36,11,L 2,17970,2:35,NaN

#### Canucks Capacity

In [4]:
capacity = pd.read_csv('../data/canucks/arena_capacity.csv')

In [5]:
capacity.head()

,Rank,Arena,Capacity(Seating capacity only),City,Country,Home Team
0,1,Bell Centre,"21,273",Montreal,Canada,Montreal Canadiens
1,2,United Center,"19,717",Chicago,United States,Chicago Blackhawks
2,3,Wells Fargo Center,"19,537",Philadelphia,United States,Philadelphia Flyers
3,4,Little Caesars Arena,"19,515",Detroit,United States,Detroit Red Wings
4,5,Scotiabank Saddledome,"19,289",Calgary,Canada,Calgary Flames

In [6]:
capacity_dict = dict(zip(capacity['Home Team'], capacity['Capacity(Seating capacity only)']))
capacity_dict

{'Montreal Canadiens': '21,273',
 'Chicago Blackhawks': '19,717',
 'Philadelphia Flyers': '19,537',
 'Detroit Red Wings': '19,515',
 'Calgary Flames': '19,289',
 'Florida Panthers': '19,250',
 'St. Louis Blues': '19,150',
 'Tampa Bay Lightning': '19,092',
 'Buffalo Sabres': '19,070',
 'Vancouver Canucks': '18,910',
 'Toronto Maple Leafs': '18,800',
 'Carolina Hurricanes': '18,680',
 'Ottawa Senators': '18,652',
 'Edmonton Oilers': '18,641',
 'Dallas Stars': '18,532',
 'Washington Capitals': '18,506',
 'Pittsburgh Penguins': '18,387',
 'Los Angeles Kings': '18,230',
 'Columbus Blue Jackets': '18,144',
 'Minnesota Wild': '18,064',
 'Colorado Avalanche': '18,007',
 'New York Rangers': '20,789',
 'Boston Bruins': '17,850',
 'San Jose Sharks': '17,562',
 'Vegas Golden Knights': '17,500',
 'Anaheim Ducks': '17,174',
 'Arizona Coyotes': '17,125',
 'Nashville Predators': '17,113',
 'New Jersey Devils': '16,514',
 'New York Islanders': '15,813',
 'Winnipeg Jets': '15,294'}

In [9]:
attendance['Unnamed: 2'] = attendance['Unnamed: 2'].fillna('Home')

In [10]:
attendance

,GP,Date,Unnamed: 2,Opponent,GF,GA,Unnamed: 6,Unnamed: 7,W,L,OL,Streak,Att.,LOG,Notes,Capacity
0,1,2018-10-03,Home,Calgary Flames,5,2,W,NaN,1,0,0,W 1,18870,2:31,NaN,Calgary Flames
1,2,2018-10-06,@,Calgary Flames,4,7,L,NaN,1,1,0,L 1,18688,2:39,NaN,Calgary Flames
2,3,2018-10-09,@,Carolina Hurricanes,3,5,L,NaN,1,2,0,L 2,11932,2:35,NaN,Carolina Hurricanes
3,4,2018-10-11,@,Tampa Bay Lightning,4,1,W,NaN,2,2,0,W 1,19092,2:23,NaN,Tampa Bay Lightning
4,5,2018-10-13,@,Florida Panthers,3,2,W,NaN,3,2,0,W 2,11953,2:32,NaN,Florida Panthers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,78,2019-03-28,Home,Los Angeles Kings,3,2,W,SO,33,35,10,W 1,18524,2:38,NaN,Los Angeles Kings
78,79,2019-03-30,Home,Dallas Stars,3,2,W,SO,34,35,10,W 2,18663,2:42,NaN,Dallas Stars
79,80,2019-04-02,Home,San Jose Sharks,4,2,W,NaN,35,35,10,W 3,18524,2:22,NaN,San Jose Sharks
80,81,2019-04-04,@,Nashville Predators,2,3,L,NaN,35,36,10,L 1,17669,2:24,NaN,Nashville Predators
81,82,2019-04-06,@,St. Louis Blues,2,3,L,SO,35,36,11,L 2,17970,2:35,NaN,St. Louis Blues

In [11]:
attendance['Capacity'] = attendance['Opponent']

In [12]:
home_mask = attendance['Unnamed: 2'] == 'Home'
away_mask = attendance['Unnamed: 2'] == '@'

In [13]:
attendance['Capacity'][home_mask] = capacity_dict['Vancouver Canucks']

C:\Users\mitch\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [25]:
attendance['Capacity'][away_mask] = attendance['Capacity'][away_mask].map(capacity_dict)

C:\Users\mitch\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [26]:
attendance

,GP,Date,Unnamed: 2,Opponent,GF,GA,Unnamed: 6,Unnamed: 7,W,L,OL,Streak,Att.,LOG,Notes,Capacity
0,1,2018-10-03,Home,Calgary Flames,5,2,W,NaN,1,0,0,W 1,18870,2:31,NaN,"18,910"
1,2,2018-10-06,@,Calgary Flames,4,7,L,NaN,1,1,0,L 1,18688,2:39,NaN,"19,289"
2,3,2018-10-09,@,Carolina Hurricanes,3,5,L,NaN,1,2,0,L 2,11932,2:35,NaN,"18,680"
3,4,2018-10-11,@,Tampa Bay Lightning,4,1,W,NaN,2,2,0,W 1,19092,2:23,NaN,"19,092"
4,5,2018-10-13,@,Florida Panthers,3,2,W,NaN,3,2,0,W 2,11953,2:32,NaN,"19,250"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,78,2019-03-28,Home,Los Angeles Kings,3,2,W,SO,33,35,10,W 1,18524,2:38,NaN,"18,910"
78,79,2019-03-30,Home,Dallas Stars,3,2,W,SO,34,35,10,W 2,18663,2:42,NaN,"18,910"
79,80,2019-04-02,Home,San Jose Sharks,4,2,W,NaN,35,35,10,W 3,18524,2:22,NaN,"18,910"
80,81,2019-04-04,@,Nashville Predators,2,3,L,NaN,35,36,10,L 1,17669,2:24,NaN,"17,113"
81,82,2019-04-06,@,St. Louis Blues,2,3,L,SO,35,36,11,L 2,17970,2:35,NaN,"19,150"

In [45]:
attendance['Capacity'] = attendance['Capacity'].str.replace(',', '')

In [50]:
attendance['Capacity'] = pd.to_numeric(attendance['Capacity'])

In [51]:
type(attendance['Capacity'][1])

numpy.int64

In [52]:
attendance['Attendance Ratio'] = attendance['Att.']/attendance['Capacity']

In [53]:
attendance

,GP,Date,Unnamed: 2,Opponent,GF,GA,Unnamed: 6,Unnamed: 7,W,L,OL,Streak,Att.,LOG,Notes,Capacity,Attendance Ratio
0,1,2018-10-03,Home,Calgary Flames,5,2,W,NaN,1,0,0,W 1,18870,2:31,NaN,18910,0.997885
1,2,2018-10-06,@,Calgary Flames,4,7,L,NaN,1,1,0,L 1,18688,2:39,NaN,19289,0.968842
2,3,2018-10-09,@,Carolina Hurricanes,3,5,L,NaN,1,2,0,L 2,11932,2:35,NaN,18680,0.638758
3,4,2018-10-11,@,Tampa Bay Lightning,4,1,W,NaN,2,2,0,W 1,19092,2:23,NaN,19092,1.000000
4,5,2018-10-13,@,Florida Panthers,3,2,W,NaN,3,2,0,W 2,11953,2:32,NaN,19250,0.620935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,78,2019-03-28,Home,Los Angeles Kings,3,2,W,SO,33,35,10,W 1,18524,2:38,NaN,18910,0.979588
78,79,2019-03-30,Home,Dallas Stars,3,2,W,SO,34,35,10,W 2,18663,2:42,NaN,18910,0.986938
79,80,2019-04-02,Home,San Jose Sharks,4,2,W,NaN,35,35,10,W 3,18524,2:22,NaN,18910,0.979588
80,81,2019-04-04,@,Nashville Predators,2,3,L,NaN,35,36,10,L 1,17669,2:24,NaN,17113,1.032490
81,82,2019-04-06,@,St. Louis Blues,2,3,L,SO,35,36,11,L 2,17970,2:35,NaN,19150,0.938381

In [55]:
mask = attendance['Attendance Ratio'] > 1
attendance['Attendance Ratio'] = attendance['Attendance Ratio'].where(~mask, 1)

In [56]:
attendance

,GP,Date,Unnamed: 2,Opponent,GF,GA,Unnamed: 6,Unnamed: 7,W,L,OL,Streak,Att.,LOG,Notes,Capacity,Attendance Ratio
0,1,2018-10-03,Home,Calgary Flames,5,2,W,NaN,1,0,0,W 1,18870,2:31,NaN,18910,0.997885
1,2,2018-10-06,@,Calgary Flames,4,7,L,NaN,1,1,0,L 1,18688,2:39,NaN,19289,0.968842
2,3,2018-10-09,@,Carolina Hurricanes,3,5,L,NaN,1,2,0,L 2,11932,2:35,NaN,18680,0.638758
3,4,2018-10-11,@,Tampa Bay Lightning,4,1,W,NaN,2,2,0,W 1,19092,2:23,NaN,19092,1.000000
4,5,2018-10-13,@,Florida Panthers,3,2,W,NaN,3,2,0,W 2,11953,2:32,NaN,19250,0.620935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,78,2019-03-28,Home,Los Angeles Kings,3,2,W,SO,33,35,10,W 1,18524,2:38,NaN,18910,0.979588
78,79,2019-03-30,Home,Dallas Stars,3,2,W,SO,34,35,10,W 2,18663,2:42,NaN,18910,0.986938
79,80,2019-04-02,Home,San Jose Sharks,4,2,W,NaN,35,35,10,W 3,18524,2:22,NaN,18910,0.979588
80,81,2019-04-04,@,Nashville Predators,2,3,L,NaN,35,36,10,L 1,17669,2:24,NaN,17113,1.000000
81,82,2019-04-06,@,St. Louis Blues,2,3,L,SO,35,36,11,L 2,17970,2:35,NaN,19150,0.938381

In [57]:
attendance.to_csv('../data/canucks/canucks_201819_attendance.csv')