In [1]:
import numpy as np
import pandas as pd
import glob

pd.set_option('max_colwidth', 1000)

In [2]:
#create dataframe with all csvs in this folder concatenated
raptors = pd.concat([pd.read_csv(f) for f in glob.glob('data/tweets/raptors/raw/*.csv')], ignore_index = True)

In [3]:
raptors

,Unnamed: 0,Date,Game Location,ID,Tweet,User
0,0,2018-10-10 02:53:14+00:00,Philadelphia,1049855345592557569,She like a bear claw/ She Like Kawhi Leonard/ She tryna lock a nigga right down but imma spin her (OFF THE TOP FREESTYLE) #uproarchallenge #YOUMIDASWELL #offthetop #Freestyle #rap… https://www.instagram.com/p/BovInywlZAW/?utm_source=ig_twitter_share&amp;igshid=j0snyt02l6o6,Youmidaswell
1,1,2018-10-10 12:48:14+00:00,Toronto,1050005082748702722,"I’m a Kawhi fan! Just like him, when I laugh, I laugh hard! @Toronto, Ontario https://www.instagram.com/p/BowMkOSAyxS/?utm_source=ig_twitter_share&amp;igshid=pjnvdyobmhaq",sivedahk
2,2,2018-10-16 15:25:57+00:00,Toronto,1052219099911094272,NBA IS BACK! : ( tolecover ) . . . . #torontoraptors #kawhileonard #nba #canada #raptors #sethcurry #kawhi #derozan #dannygreen #kylelowry #jusufnurkic #sergeibaka… https://www.instagram.com/p/Bo_7iYwg2rp/?utm_source=ig_twitter_share&amp;igshid=14na9kf9c438n,MikeandDrewShow
3,3,2018-10-16 15:33:36+00:00,Los Angeles,1052221027768573954,The NBA is BACK! #NBA #Basketball #Hoops #TrusttheProcess #Kawhi #Raptors #WetheNorth#Comedy #Toronto #Canada #Spurs #SanAntonio #Lakers #Warriors #Celtics #Bulls #Knicks @Los… https://www.instagram.com/p/Bo_8TtwlpLk/?utm_source=ig_twitter_share&amp;igshid=5l2105hiczod,Aye_Artiiee
4,4,2018-10-16 15:33:36+00:00,Los Angeles,1052221027768573954,The NBA is BACK! #NBA #Basketball #Hoops #TrusttheProcess #Kawhi #Raptors #WetheNorth#Comedy #Toronto #Canada #Spurs #SanAntonio #Lakers #Warriors #Celtics #Bulls #Knicks @Los… https://www.instagram.com/p/Bo_8TtwlpLk/?utm_source=ig_twitter_share&amp;igshid=5l2105hiczod,Aye_Artiiee
...,...,...,...,...,...,...
4722,3701,2019-04-10 22:42:48+00:00,Toronto,1116109300177489922,You Wanna Play The Raptors First Round?,Miss_Angel_Baby
4723,3702,2019-04-10 22:50:33+00:00,Orlando,1116111251887804417,"So who do we want to face?!? Bucks, Raptors, or 76ers?! #puremagic",Gosurf911
4724,3703,2019-04-10 23:13:49+00:00,Toronto,1116117106439925765,"He coached Kyle, FVV, Siakam (who’s a totally different player), OG, Norm and ibaka (being used properly unlike how Casey used him). Raptors are a totally different squad Plus Casey notoriously got outcoached. I can’t wait to sweep them",Arysaf
4725,3704,2019-04-10 23:38:59+00:00,San Francisco,1116123441935994880,You need a meme clip of moldune (probably misspelled) from Jurassic park #1 when he gets eaten by the raptor.,JSRW1986
4726,3705,2019-04-10 23:52:37+00:00,Oklahoma City,1116126871547207680,The Raptors would be a pretty nice fit for him....,_Poochie66

In [4]:
#check for NaN
raptors.isna().sum()

Unnamed: 0       0
Date             0
Game Location    0
ID               0
Tweet            0
User             0
dtype: int64

In [5]:
raptors.drop(['Unnamed: 0'], axis=1, inplace=True)

In [6]:
raptors['Date'] = pd.to_datetime(raptors['Date'])
EST = pd.Timedelta('5 hours')
raptors['Date'] = raptors['Date'] - EST

In [7]:
#remove hyperlinks
raptors['Tweet'] = raptors['Tweet'].str.replace('\w+:\/\/\S+', '', case=False)

In [8]:
#drop duplicate tweets
raptors = raptors.drop_duplicates('Tweet')

In [9]:
raptors.reset_index(drop=True, inplace=True)

In [10]:
raptors

,Date,Game Location,ID,Tweet,User
0,2018-10-09 21:53:14+00:00,Philadelphia,1049855345592557569,She like a bear claw/ She Like Kawhi Leonard/ She tryna lock a nigga right down but imma spin her (OFF THE TOP FREESTYLE) #uproarchallenge #YOUMIDASWELL #offthetop #Freestyle #rap…,Youmidaswell
1,2018-10-10 07:48:14+00:00,Toronto,1050005082748702722,"I’m a Kawhi fan! Just like him, when I laugh, I laugh hard! @Toronto, Ontario",sivedahk
2,2018-10-16 10:25:57+00:00,Toronto,1052219099911094272,NBA IS BACK! : ( tolecover ) . . . . #torontoraptors #kawhileonard #nba #canada #raptors #sethcurry #kawhi #derozan #dannygreen #kylelowry #jusufnurkic #sergeibaka…,MikeandDrewShow
3,2018-10-16 10:33:36+00:00,Los Angeles,1052221027768573954,The NBA is BACK! #NBA #Basketball #Hoops #TrusttheProcess #Kawhi #Raptors #WetheNorth#Comedy #Toronto #Canada #Spurs #SanAntonio #Lakers #Warriors #Celtics #Bulls #Knicks @Los…,Aye_Artiiee
4,2018-10-17 14:24:42+00:00,Los Angeles,1052641571907260416,The internets really is undefeated! #Repost @bobmenery • • • • • This video broke youtube....literally. Way too many Ripper Magoos for Kawhi Leonard. Tag someone to get this caught…,ImMellowMadness
...,...,...,...,...,...
3916,2019-04-10 17:42:48+00:00,Toronto,1116109300177489922,You Wanna Play The Raptors First Round?,Miss_Angel_Baby
3917,2019-04-10 17:50:33+00:00,Orlando,1116111251887804417,"So who do we want to face?!? Bucks, Raptors, or 76ers?! #puremagic",Gosurf911
3918,2019-04-10 18:13:49+00:00,Toronto,1116117106439925765,"He coached Kyle, FVV, Siakam (who’s a totally different player), OG, Norm and ibaka (being used properly unlike how Casey used him). Raptors are a totally different squad Plus Casey notoriously got outcoached. I can’t wait to sweep them",Arysaf
3919,2019-04-10 18:38:59+00:00,San Francisco,1116123441935994880,You need a meme clip of moldune (probably misspelled) from Jurassic park #1 when he gets eaten by the raptor.,JSRW1986
3920,2019-04-10 18:52:37+00:00,Oklahoma City,1116126871547207680,The Raptors would be a pretty nice fit for him....,_Poochie66

In [11]:
raptors.to_csv('data/tweets/raptors/raptors_tweets_concat_raw.csv')

In [12]:
def remove_query(i):
    remove_index = raptors[raptors['Tweet'].str.contains(i, case=False)].index
    raptors.drop(remove_index, inplace = True)

In [13]:
raptors[raptors['Tweet'].str.contains('ford', case=False)]

,Date,Game Location,ID,Tweet,User
226,2019-03-12 13:24:56+00:00,Los Angeles,1105535157363052544,#FutureWife @LindseyKevitch @RobertDowneyJr @RobertIger My video recording #IronMan @SEANxLONG @hasbro @Comic_Con #ClipperNation @LAClippers to @TMobile @LasVegasSun @NellisAFB @seanhannity @StanfordLawMag @caafoundation @Raiders @AB84 @kawhileonard @Steven_Ballmer @JeffBezos – at T-Mobile,W_ProphetBalik
828,2018-10-12 10:06:04+00:00,Phoenix,1050764547164901382,We have 7 BRAND NEW RAPTORS for sale for $500 over INVOICE!!! Contact me if interested at 702-460-6570 and share this with your Raptor enthusiasts!!! peoriaford #DealDoctor fordperformance…,AdamZito
840,2018-10-15 18:22:37+00:00,Portland,1051976671060848640,The first oil change and tire rotation. They grow up so fast! #sentimental #Raptor #Gen2 #FordPerformance #F150 #Ford @Courtesy Ford Lincoln,TheWhalen
846,2018-10-16 18:57:03+00:00,Phoenix,1052347723020681217,20” Flow Forged venom_rex VR-601 | Made exclusively for 2009+ Ford F150 and F150 Raptor &#13;___ Order your set at | 480-968-1314 @Wheel Specialists' Andre Roberts at your service,wheelspecialist
901,2018-10-19 19:40:35+00:00,Toronto,1053445843070537728,Let’s Go Raptors!! @fordcanada #gofurther @Scotiabank Arena,sjmcgrath11
919,2018-10-20 09:50:11+00:00,Detroit,1053659649902284802,What's in the box???? #fordperformance #fordsofinstagram #ecoboost #f150 #ford #raptor #f150xlt #fordtrucksontario #fordracing @LaSalle,joshabela
949,2018-10-22 18:06:38+00:00,Portland,1054509360863416320,"Guess my back to work truck (when ready/doctor releases) .... I thought who needs a ford raptor? #ford #badmambajamba @Trent Best, Mortgage Advisor NMLS #115651",trentbestloans
970,2018-10-23 22:06:08+00:00,Phoenix,1054932020579782657,All Steel Laser cut Raptor Style Superduty grille’s ship link in bio #sema #semashow #ford #raptorstyle #raptor #superduty #f250 #f350 #f450 #custom #madeinusa #builtnotbought #trucks…,UniqueAutoDepot
978,2018-10-24 16:30:28+00:00,Phoenix,1055209937868079105,"Shop this exclusive Raptor Style Superduty grille today, ALL % Made in the USA #alumiduty #superduty #f250 #f350 #f450 #ford #raptor #fordraptor #sema #sema2018 #builtnotbought…",UniqueAutoDepot
1027,2018-10-26 21:29:24+00:00,Salt Lake City,1056009943286013952,Insane experience with @FPRacingSchool out in the saltlakecity_utah #mountains testing the limits on the ford #raptor. Great guys leading the way for a full day of driving in real…,Abejiv
1163,2018-11-13 15:29:04+00:00,Detroit,1062442241220694016,°°° This Beast is looking for a New Home ~~ 2012 Ford F150 #Raptor With only 112981 km Monster will not be here long for this price Only $$$39979 plus tax This special buy is…,kingss23live
1169,2018-11-14 17:19:56+00:00,Los Angeles,1062832530582392837,Sitting in our showroom is this available #Shelby #Raptor. Swipe to see more and call to learn more! 888-230-2741 #Ford #GalpinFord #ShelbyRaptor #FordRaptor #GetitatGalpin #LosAngeles…,galpinmotors
1190,2018-11-15 22:35:34+00:00,Orlando,1063274351427035137,"Only $67,777.00 2018 Ford F-150 Raptor SuperCrew 4x4 Black Black Leather with Orange Accent 802A Package Twin Panel Moonroof Exterior…",Auto_Export_USA
1296,2018-11-27 19:37:59+00:00,Denver,1067578314112606208,"Adding weight carrying capacity to a 2018 Ford F-150 Raptor along with some snow traction! #webuildtrucks #ftgbuilt #modyourtruck #fordraptor #fordtrucks @Four To Go, Inc.",FTGArcticcat
1345,2018-12-02 17:42:40+00:00,Dallas,1069361232669536256,Road trippin to OKC for done Christmas shopping. • • • • #raptor #fordraptor #bangolufsen #bando #ford #okc #oklahoma #christmastime @I-35 South,SgtGains
1376,2018-12-05 18:46:57+00:00,Phoenix,1070464572539224066,"20” Flow Forged Venom Rex VR-Made Exclusively for 2009+ Ford F-150and F-150 Raptor ___ Available at | 480-968-1314 @Wheel Specialists, Inc.",wheelspecialist
1404,2018-12-07 13:49:32+00:00,Dallas,1071114504044449792,"Marcus stepped up his truck game, and snagged the cleanest Raptor around! Thanks for your business, fella! #DallasAutoExchange #Raptor #FordRaptor #Ford #FordTruck #FordF150 #F150…",DallasAutoExch
1405,2018-12-07 13:59:29+00:00,Phoenix,1071117005154082818,"All 2018 Raptors for $1,500 UNDER MSRP! Only 10 left to choose from at peoriaford ! Contact me at 702-460-6570 if interested!!! fordperformance #DealDoctor…",AdamZito
1412,2018-12-08 12:07:03+00:00,Phoenix,1071451101558423552,"FACT: it is always better to give than receive Visit Peoria Ford today, Saturday, December 8 for #OperationFillTheTruck and you could win a new 2019 ford Raptor or $50,000 cash just by…",AZFoothillsMag
1424,2018-12-10 15:12:33+00:00,New York,1072222558769033217,"Monday Blues cause the time has come…Don’t forget to swipe right!⁣ ⁣ 2018 WRAPTOUR FOR SALE⁣ ⁣ For Sale 2018 Ford Raptor. ⁣ Current Miles 11,000⁣ ⁣ Asking $66,000 OBO⁣ ⁣ Oxford…",C_GERM
1432,2018-12-10 16:23:57+00:00,Los Angeles,1072240528282935296,"ford booth at the 2018LAautoshow | I know most of us cant wait for the release of the new Ranger, it was a treat to see a GT, Raptor and of course the #Lego giveaways | #Ford #FordGT…",CoiTajoDesigns
1438,2018-12-10 22:06:53+00:00,Los Angeles,1072326828650582016,Blue got me RAPTOR ‘round her finger #yayfordinosaurpuns @Universal Studios Hollywood,erica_macd
1534,2018-12-22 23:36:14+00:00,Sacramento,1076697968638640129,2014 Ram 1500 Tesla Screen Also available for select Fords Like our Facebook Page for $20 off your next purchase. #big #screen #dodge #ford #ram #ram1500 #f150 #f250 #raptor #tesla…,EAtintandwraps
1538,2018-12-23 20:05:48+00:00,Los Angeles,1077007401319059458,Where do you adventure in your #Raptor? Some of our employees like to take theres to Angeles Crest in search of snow! Photo by @blonde_danny #Ford #Galpin #GalpinFord #GetitatGalpin…,Galpinford
1551,2018-12-27 09:50:20+00:00,Indianapolis,1078302061937258496,Your choice: 2 Bullits 1 GT350 8 Raptors 1 2017 Ford Focus @Andy Mohr Ford,Jblakely_
1577,2018-12-31 07:09:52+00:00,Orlando,1079711233492901888,#Ford #F150 #Raptor Carbon Ceramic 30% front doors &amp; 15 rear windows. Clear Ceramic Whole Windshield. #TintMan 407-678-TINT(8468) @Tint Man Window Tinting Longwood,windowtintingfl
1766,2019-01-16 13:26:05+00:00,Los Angeles,1085604114082480128,"Hotwheels Ford Raptor Tacos are very good on a rainy day . Visit my store Playdays Collectibles and check out my inventory at 12310 penn street, whittier CA 90602.10-6:30pm. On…",playdaysdiecast
1805,2019-01-19 02:08:49+00:00,Los Angeles,1086520841439830016,"An awesome Hotwheels Ford Raptor . Visit my store Playdays Collectibles and check out my inventory at 12310 penn street, whittier CA 90602.10-6:30pm. On Thursdays we close at 5pm. Open…",playdaysdiecast
1831,2019-01-22 17:01:19+00:00,San Francisco,1087832606551486465,Come check out this 2018 #FordRaptor #chooseguz #raptor #fordtrucks #fordraptor in stock and ready for immediate delivery. #@Choose Guz at Putnam Chevrolet Cadillac Buick GMC,tguzman661
1946,2019-02-05 11:16:40+00:00,Brooklyn,1092819305094238208,Dying Breed. #raptor #ford #nyc #concreteplant #atlas #leadfootgray @Atlas Transit Mix Corp,TheeVinnyP
1954,2019-02-07 06:14:33+00:00,Charlotte,1093468050110758912,Good Thursday morning! Ford Raptor got a Maintenance Detail &amp; c2v3 coating Package. Make your appointment soon. Gtechniq ceramic coating Specialist of gastonia!!! www.bwrightdetail…,bwrightdetail
2060,2019-02-19 10:46:31+00:00,Phoenix,1097885145300901888,"The VR-602 from venom_rex is one of the lightest 17” Flow Forged wheels available. Guaranteed fitment for the 2009+ Ford F150 / Raptor, 2002+ Toyota Tacoma, 2002+ Toyota 4Runner, 2007+…",wheelspecialist
2121,2019-02-26 14:44:11+00:00,Miami,1100481671235846144,#2017 #ford #raptor #karconnection #miami #fromoldtonew #wedoitall @KAR Connection,Karconn
2149,2019-03-01 09:36:25+00:00,New York,1101491382869319680,Building the costco gazebo. #costco #backyard #greatteam #teamwork #milwaukeetools #ford #raptor @Costco,SwingsetInstall
2168,2019-03-02 09:26:20+00:00,Oklahoma City,1101851235408261120,Even at Starbucks at 8 am on a Saturday she looks damn good. • • • • #fordraptor #oklahoma #lifeontheroad #starbucks #fordperformance #raptor #raptoraddiction #raptorlights @Nichols…,SgtGains
2202,2019-03-05 08:38:56+00:00,Toronto,1102926471767588867,"Call me Chris Pratt, I be chilling with this Raptor . . . . . . . #mooseknucklescanada #parka #popupmuseum #ugg #uggboots #joejeans #zara #zaramens #dressshirt #tomfordglasses #the7to…",sysimonliu
2223,2019-03-09 05:25:33+00:00,Detroit,1104327354082459648,Pre Raptor! #fomoco #builtfordtough #rougepride @Ford River Rouge Complex,mattdamon_s
2408,2019-03-13 18:42:42+00:00,Toronto,1105977515045257216,A exciting new #SunLifeDunkForDiabetes online program coming from our team and in partnership with @LuminoHealth @NBACanada @Raptors Join today!,kdzanier
2769,2019-03-20 20:54:07+00:00,Chicago,1108547301545558016,"Historically, Al Horford dominates Marc Gasol. I'll bet on the Raptors choking in the playoffs again.",tianrossi
3167,2019-03-26 20:35:57+00:00,Toronto,1110717056830320640,Raptor. . . This new #ford #raptor was in for an extensive #ppf install via advancedautomotivefilms and a #newcarprep and @cquartzfinest #resrerve application. . . #cquartz…,gtaindetail
3182,2019-03-26 21:38:09+00:00,Portland,1110732712287977473,My bday is tomorrow all I want are AirPods and a Ford Raptor,liliuzivert
3221,2019-03-28 05:38:34+00:00,New Orleans,1111215999460663297,Good friends push each other outside their comfort zones to grow into better people. It has taken me 6 years to push my brother tc_comeaux to finally buy the ford_raptors he’s always…,MikeBrandner
3412,2019-04-01 10:07:55+00:00,Minneapolis,1112733335296638976,I stopped fucking with Ford cars a while back but them Ford Raptors be nasty!,abla3000
3479,2019-04-02 13:00:19+00:00,Toronto,1113139109193633793,It's almost playoff time and @FordCanada is offering you the chance to win a pair of tickets to one of our Leafs or Raptors Playoff Parties at Real Sports Bar &amp; Grill. Enter here: #FordPlayoffDrive,TheFordFANatic
3566,2019-04-04 11:30:35+00:00,Toronto,1113841303639425029,"If you haven’t entered this yet, you should! It’s so much fun and @FordCanada treats you right (hello complimentary food/drinks) while watching your fav team @Raptors or @MapleLeafs at @realsportsto #LeafsForever #WeTheNorth",TheFordFANatic
3577,2019-04-04 17:07:47+00:00,Salt Lake City,1113926161325641728,"But will have a huge impact on the environment & affordability in our modern economical world. Renewables are disruptive to maintaining grid integrity, trash wild landscapes, fry large apex raptors, &amp; need gas generators 80% of the time to back them up.",Paul_Davidsen
3578,2019-04-04 17:09:33+00:00,Detroit,1113926605594820609,"Every time I move a Raptor I get the urge to trade my truck in for one. Side note is between those two raptors there is a $10k difference. #fordraptor #gorgeous @Dearborn, Michigan",ToTheExcursion
3655,2019-04-06 09:10:07+00:00,Houston,1114530730531524608,12U Boys - Pool A - Katy Raptors 2025 def. TJ Ford Blue 41-28 #OFFDAHOOK @exposurebball,BrianJolivette
3670,2019-04-06 14:54:43+00:00,Denver,1114617449754845187,"Raptor Row. Biggest selection in Colorado, come make an offer @Groove Ford",matturland
3829,2019-04-08 20:59:35+00:00,Houston,1115434047738654720,Guess we all need a fucking Ford raptor,JustinArsalon1
3895,2019-04-10 06:38:35+00:00,Charlotte,1115942146610085889,Ford Raptor on Velgen Forged VFT8 20” Car Owner steve_buchanan phantomblackphotography #velgenforged #velgentruckseries #vft8 #ford #raptor #fordraptor #trucks #fords #truckstuff…,Velgenwheels

In [14]:
remove_query('ford')

C:\Users\mitch\Anaconda3\envs\neuralnetworks\lib\site-packages\pandas\core\frame.py:4117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [15]:
raptors[raptors['Tweet'].str.contains('racing', case=False)]

,Date,Game Location,ID,Tweet,User
2295,2019-03-11 14:56:36+00:00,Salt Lake City,1105195840505708544,"Ahhhh @KenBlockRacing is on my flight...I just want to rally our raptors together in UT, instead...I see him on a plane. #typical #raptortwins #canigetapicture #hoonigan – at Salt Lake City International Airport (SLC)",CloudArcs
2630,2019-03-17 23:09:28+00:00,Toronto,1107494200457736194,"Finally got time to snap a pic of the new tailights and I absolutely love the look Thanks to raptor_racing for these beauties, and specdtuning for creating these gorgeous…",VapidFuture

In [16]:
remove_query('racing')

In [17]:
raptors[raptors['Tweet'].str.contains('universal', case=False)]

,Date,Game Location,ID,Tweet,User
839,2018-10-15 18:05:13+00:00,Orlando,1051972289468792832,"Greg go to visit the Raptor he named when it hatched 2 years ago. That's not Betsy behind him, btw. @Universal Studios Island Of Adventures- Jurassic Park River Adventure",BrevonDarksteel
917,2018-10-20 08:27:08+00:00,Los Angeles,1053638749068779520,Hi blue You're a good girl! #universalstudios #hollywood #jurrasicworld #jurassicpark #raptor #ユニバ @Universal Studios Hollywood,MYK____25
1006,2018-10-26 12:08:05+00:00,Orlando,1055868679835938816,We had such a blast!! We survived this encounter with a Raptor!! More pics to come! #raptor #universalstudios #universal #universalorlando #universalstudiosorlando #jurassicworld…,NolanRyan680
1054,2018-10-28 22:10:29+00:00,Los Angeles,1056745055103389702,Raptor petting time - #LA #california @Universal Studios Hollywood,javituiran
1084,2018-11-01 15:27:43+00:00,Orlando,1058093248776978433,Meet Blue - Raptor Encounter jurassicworld @universalorl @dana_egan • • • • • • • • • • #dinosaur #instago #travel #trip #universalstudios #vacation #ig_worldclub #traveldeeper…,clloyd101
1116,2018-11-06 18:11:06+00:00,Los Angeles,1059946305458462720,"Raptor 'trainer': What's in your bag? Blue is really reacting to it. Me: Dinosaur snacks. Just kidding, I'm vegetarian. Trainer: Thank god. Your life choice has saved you. @Universal…",Megan_Mercury
1183,2018-11-15 05:36:39+00:00,Los Angeles,1063017931477413888,"Universal Studios Hollywood, Raptor Encounter - Los Angeles, California, United States of America #universalstudios #universalstudioshollywood #universal #hollywood #losangeles #usa…",iamitv99
1211,2018-11-19 09:18:07+00:00,Orlando,1064523216599822338,"@prattprattpratt thinks he's special... #blue #raptor #universalstudios @Orlando, Florida",unB10
1213,2018-11-19 18:51:31+00:00,Los Angeles,1064667517522796544,"The single coolest thing I’ve ever done with a Raptor! I love you, Blue! #nilissues #universalstudios #universalstudioshollywood #ush #universal #jurassicpark #jurassicworld #blue…",AbsoluteNil
1222,2018-11-20 19:43:45+00:00,Los Angeles,1065043051121381377,"Raptor encounter... but really, who encountered who!?! #universalstudios #raptorencounter #imnotscaredofblue #jurassicpark #jurassicworld #blue #raptor…",ThisisMikki
1294,2018-11-27 13:12:33+00:00,Los Angeles,1067481318651396102,I think I found the perfect jacket in the perfect size . #myfakesmilesaysitall • • • • • • #jurassicjen #jendurst #tues #universalstudios #itfits #jurassicgirl #raptor #dinostyle…,thejurassicjen
1358,2018-12-03 23:27:57+00:00,Orlando,1069810516145655808,"Picture of the day! brookiebeth matthewhess1981 #blue #raptor #whydoialwaysgetpickedonbytheraptors #ohana #universal #love #blessed @Universal Orlando, Island…",Christen_08
1359,2018-12-04 02:45:34+00:00,Orlando,1069860245114159104,This Raptor was so cute! ~ #JenLoAssassin #Universal #UniversalStudios #IslandsOfAdventure #JurassicPark #Raptor #Dinosaur #AdventureIsland #Weekend #MiniVacay #Orlando #FL #Vacation…,JenLoAssassin
1362,2018-12-04 16:27:08+00:00,Los Angeles,1070067000175542273,Raptor Selfie!! * * * * #universalstudios #universalstudioshollywood #raptorselfie #raptor #jurassicworld @Universal Studios Hollywood,rumour2577
1447,2018-12-12 10:23:58+00:00,Orlando,1072874709031796738,Not sure why Blue only wanted to eat me... #jurassicpark #blue #raptor #triednottoactscared #ifailed @Universal Studios Island Of Adventures- Jurassic…,feistybatmom
1514,2018-12-21 13:03:53+00:00,Orlando,1076176443917434880,Met some dinosaurs today. They kinda scared me. #porg #porgs #porglife #universalstudios #porgsofinstagram @Raptor Encounter,petetheporg
1536,2018-12-23 06:46:04+00:00,Orlando,1076806138136612865,"Last night we did the Raptor Encounter. ((Video at the end. Please excuse my nervous laugh.... )) @Universal Orlando, Island of Adventures",marjorierose86
1537,2018-12-23 06:48:21+00:00,Orlando,1076806714069053440,Ryan was so nervous leading up to the Raptor encounter. I’m sure he doesn’t have any nails left. @Universal Studios Island Of Adventures- Jurassic Park River…,marjorierose86
1602,2019-01-03 06:02:01+00:00,Los Angeles,1080781321130164224,Check out the raptor at #universalstudioshollywood they’re pretty cool. #jurassicworldride @unistudios @themeparkfrog jurassicworldevolution @Universal Studios Hollywood,savvynana123
1806,2019-01-19 09:21:11+00:00,Orlando,1086629647297720321,Me & my new (quite) friend Blue the raptor. #asfotosdafestaficaramotimas @Universal Studios Island Of Adventures- Jurassic Park River Adventure,meuiaiameuioio
1822,2019-01-20 12:09:31+00:00,Orlando,1087034400502624257,Eye still see you @universalorl @Raptor Encounter,dfiore
1889,2019-01-30 06:13:37+00:00,Orlando,1090568712695042057,Raptor Encounter en Island of adventure Orlando @universalorl mamaexpertadisney_universal #rapencounter #islandofadventure #jurassicpark #universalstudios #jurassicpark #dinoenvivo…,ParquesTematico
2001,2019-02-10 20:52:07+00:00,Orlando,1094776060103675904,Hanging out with #blue from #jurassicworld at #islandsofadventure #universalstudios #universalstudiosorlando #orlando #florida @Raptor Encounter,geekgirl_73
2150,2019-03-01 12:26:14+00:00,Orlando,1101534120746909697,It’s a dinosauuuuur it’s a dinosauuuur #jurrasicpark #universalorlando #uoteam #newfriend #totallyreal #NOTa #puppet @Raptor Encounter,2InfinityNByond
2179,2019-03-03 16:55:34+00:00,Orlando,1102326677642731525,We got to meet Raptor BLUE yesterday!!! It cost me my face but totally worth it #Universal2019 #BLUE #JurassicPark #JurassicWorld …,Chato_Luis_305
2183,2019-03-03 17:52:28+00:00,Orlando,1102340993871896576,So we met #blue #jurassicworld #jurassicpark #universalstudios #orlando #raptor #dino #dinosaur @Raptor Encounter,dbessey78
2195,2019-03-03 22:33:54+00:00,Orlando,1102411821774827520,Donna and me meeting #blue So we met #blue #jurassicworld #jurassicpark #universalstudios #orlando #raptor #dino #dinosaur @Raptor Encounter,dbessey78
2599,2019-03-17 17:01:59+00:00,Los Angeles,1107401720244641792,Can’t forget Rebecca’s photo op with a Raptor Dinosaur. @Universal Studios Hollywood,PHChiro4life
3200,2019-03-27 08:41:13+00:00,Orlando,1110899578155532289,#UniversalMoments #Blue #JurassicPark #JurassicWorld #RaptorEncounter @Raptor Encounter,JoniLeBouef
3397,2019-03-31 17:42:56+00:00,Los Angeles,1112485457366003717,This is a picture of my friend Michael and I from Universal Studios a few months ago. I forgot I had it and it really amuses me. Those are Raptor masks in the gift shop.…,rkolder
3912,2019-04-10 16:09:41+00:00,Atlanta,1116085870195609600,(2/2) Well @UniversalORL DMed me and asked if our class wanted to name a raptor... well of course we did! So here is the birth certificate. My kids (being as sweet as they are) named the raptor after my grandmother-who passed away when I was little . #sharonstrong @SharonElemS,MrsKaraAMerck

In [18]:
remove_query('universal')

In [19]:
raptors[raptors['Tweet'].str.contains('jurassic', case=False)]

,Date,Game Location,ID,Tweet,User
833,2018-10-15 12:06:34+00:00,Los Angeles,1051882033591529472,Hmmm .... #Jurassicstuff #lootcrate -shirt • • • • • • #jurassicjen #jendurst #run #jurassicgirl #raptor #dinostyle #dinosaurs #dino #trex #blanket #motivationmonday #mondayvibes #hmmm…,thejurassicjen
849,2018-10-17 09:21:44+00:00,Toronto,1052565329451175938,Raptors fans... Who's coming out to the Season Opening Tailgate at Jurassic Park (officially known as Maple Leaf Square)? Check for us as we'll be down there recording part of the TRAP'D…,trapd95
892,2018-10-19 09:27:13+00:00,Orlando,1053291483036434432,We got to meet this awesome dinosaur #Blue #Raptor #Velociraptor #RaptorBlue #VelociraptorBlue #JurassicWorld @Jurrasic Park At Island Of Adventure,JoniLeBouef
905,2018-10-19 20:20:00+00:00,Salt Lake City,1053455762457026560,The real Jurassic World. Well house! . . #jurassicpark #jurassic #dino #dinosaur #reptiles #extinction #halloween #scary #trex #raptor #house #saltlakecity #slc #utah #ut #uav #drone…,Grallon
923,2018-10-20 13:11:22+00:00,Sacramento,1053710279828221954,#Rocklin #fallfestival met Rachael the #raptor #dinosaur #dinosaurs #jurassic #reporterlife @gooddaysac @tawfeeq_saif @tinamacuha @cambibrown @Johnson-Springview Park,Alisabecerra
974,2018-10-24 12:15:03+00:00,Los Angeles,1055145658154471425,It’s magic how this blanket just stays up . #nohands #magic #humpday • • • • • • #jurassicjen #jendurst #wednesday #vibing #jurassicgirl #raptor #dinostyle #dinosaurs #dino #trex…,thejurassicjen
1058,2018-10-29 12:09:01+00:00,Los Angeles,1056956080767623169,I am not sure I should be standing in the way of their argument. • • • • • • #jurassicjen #jendurst #jurassicgirl #raptor #mondayvibes #argument #dinostyle #dinosaurs #dino #trex…,thejurassicjen
1083,2018-11-01 12:25:54+00:00,Los Angeles,1058047491365572608,"I went as a Jurassic Park patron that got attacked by Raptors and then I did lol Perfect @West Hollywood, California",amyfey87
1103,2018-11-04 23:28:38+00:00,Los Angeles,1059301438365425664,"When jjtroconis yells “RAPTOR ATTACK” in the photo booth, you go full Jurassic Park. @Madera Kitchen &amp; Bar",HannahMHines
1215,2018-11-20 03:29:31+00:00,Los Angeles,1064797877581561857,let’s just say my inner fan girl was freaking out when we met Blue #jurassicworld #blue #raptorspam #savethedinos @Raptor Encounter,charrison1519
1217,2018-11-20 13:14:43+00:00,Los Angeles,1064945147350261760,I guess I can’t ride in riot_raptor47 ‘s jeep . Such horrible rules . Wait a minnnnnute I think I make the cut #rulesschmules • • • • • • #jurassicjen #jendurst #jurassicgirl #raptor…,thejurassicjen
1220,2018-11-20 17:51:27+00:00,Orlando,1065014790387613697,Jurassic Park. OH MY!!!!! @Raptor Encounter,Chrisperezhou
1224,2018-11-21 13:24:32+00:00,Los Angeles,1065310005048430592,Fine I’ll get up ! #happyhumpday • • • • • • #jurassicjen #jendurst #jurassicgirl #raptor #dinostyle #dinosaurs #dino #trex #humpday #wakeup #indoraptor #pets #jurassicparktoys…,thejurassicjen
1285,2018-11-26 00:50:35+00:00,Los Angeles,1066932207632166913,Finally! Dr Sattler and her best friend... not! #jurassicpark #dinosaur #jp #elliesattler #velociraptor #raptor #marchudson #marchudson2 #marchudson11 #hollywood #losangeles @Hollywood,MarcHudson2
1349,2018-12-03 14:42:59+00:00,Los Angeles,1069678402758737920,"Even though she pays absolutely no attention to me , she at least holds my hand . #mondaymotivation - #futureexmrsmalcolm • • • • • • #jurassicjen #jendurst #blue #jurassicgirl #raptor…",thejurassicjen
1373,2018-12-05 13:23:16+00:00,Los Angeles,1070383116471156737,I look like a worried raptor ranger And I’m taking a #selfie ! Don’t hire me . • • • • • • #jurassicjen #jendurst #toys #happyhumpday #wednesday #jurassicgirl #raptor #dinostyle…,thejurassicjen
1406,2018-12-07 14:34:45+00:00,Los Angeles,1071125883640000522,#flashbackfriday : Reminiscing on the time I walked Rexy across the Grove . (She seemed scared of the crowd.) • • • • • • #jurassicjen #jendurst #jurassicgirl #raptor #sokind #dinostyle…,thejurassicjen
1461,2018-12-13 13:12:05+00:00,Los Angeles,1073279406632771584,#throwbackthursday - to this pic that was so lovely “framed” (I also forgot I owned this shirt) • • • • • • #jurassicjen #jendurst #tbt #jurassicgirl #raptor #dinostyle #dinosaurs…,thejurassicjen
1487,2018-12-17 13:29:02+00:00,Los Angeles,1074733224432087041,Watch that hand you Grinch ! #sneak • • • • • • #jurassicjen #jendurst #grinch #jurassicgirl #raptor #dinostyle #dinosaurs #dino #trex #green #grinchmas #happyholidays #picoftheday…,thejurassicjen
1492,2018-12-19 12:06:37+00:00,Los Angeles,1075437258554175488,"This is my Resting Raptor Face. Paint me like one of your French raptors... - Jurassic Expedition. Green Suit = Xenomorphic Alien Raptor. Releases 2019. @Los Angeles, California",HunterFights
1515,2018-12-21 13:27:45+00:00,New York,1076182450961817605,#flashbackfriday : Same time last year I was Home Alone-ing with the dinos. #savethedinos • • • • • • #jurassicjen #jendurst #museum #jurassicgirl #raptor #dinostyle #dinosaurs #dino…,thejurassicjen
1622,2019-01-05 21:04:41+00:00,Orlando,1081733260202442752,Good Night T-Rex! #lasttime #trexisincharge #trex #smile #uoteam #proudteammember #15yearstocelebrate #lovemyjob #themepark #jurassicpark @Raptor Encounter,beetlejuice851
1662,2019-01-08 14:38:27+00:00,Orlando,1082723226822868992,Doing some more test painting today fixing the green tint from last night :) #fossil #phonecase #iphone #jurassicpark #skinillustrator #alcoholpaint #dirt #raptor #apple #homemade #ppi @…,NickL2814
1886,2019-01-28 19:55:58+00:00,New York,1090050887245012993,"Jurassic times calls for Jurassic measures (sorry, not sorry ) . . . . #Nike #jordans #raptors #kotd #wdywt #kicksonfire #kickstagram #jaysonmyfeet #whatsonyourfeet #wearyourkicks…",IvanZxie
1890,2019-01-30 12:20:10+00:00,Orlando,1090660956915417088,#Joey got to see #Blue yesterday at #JurassicPark at #IslandsOfAdventure yesterday! #UOAP @Raptor Encounter,JoniLeBouef
1895,2019-01-31 13:07:13+00:00,Los Angeles,1091035185561382912,One of those rainy days today #throwback #selfie #jurassic #hoodie • • • • • • #jurassicjen #jendurst ###jurassicgirl #raptor #dinostyle #dinosaurs #dino #trex…,thejurassicjen
2059,2019-02-19 01:55:39+00:00,Orlando,1097751552289316864,Raptor in the store! @Jurassic Park River Adventure,ColinB75
2077,2019-02-22 19:03:32+00:00,Orlando,1099097389497954304,"Life, uh...finds a way Baby raptor tiki mug by mondonews filled with zombie by @rene_nguyen at hansonsshoerepair . Can’t beat it #tikicocktails #jurassicpark #mondotiki…",Wallace_Design
2294,2019-03-11 13:32:00+00:00,Los Angeles,1105174550533234689,I watched whatever the newest jurassic park is called last night and now I just want a pet raptor.,flameIRL
2346,2019-03-11 20:24:18+00:00,Cleveland,1105278309691285505,"I’m sorry what? Was Toronto resting people? The raptors can’t even beat the Cavs when we want them to. Useless, cheesy ass Jurassic Park franchise.",DJ84
2375,2019-03-12 07:30:15+00:00,Washington D.C.,1105445900757938177,"I did an interview a few years ago about how useful it would be to weaponize raptors ala ""Jurassic World"". (The basic gist of it: however cool they might seem, mechanized weaponry you can store without feeding have a lot more bang for your buck.)",TomHoltzPaleo
2415,2019-03-14 07:45:19+00:00,Dallas,1106174467116617728,Clever Girl. . #Photography #Photographer #Canon80D #TeamCanon #MyCanonStory #ActionFigures #ActionFigurePhotography #JurassicWorld #JurassicPark #Raptors #RaptorsSquad #CleverGirl…,GueroVzn
2437,2019-03-14 12:47:10+00:00,Dallas,1106250430663790592,Looks more like a 6 Foot Turkey. . #Photography #Photographer #Canon80D #TeamCanon #MyCanonStory #ActionFigures #ActionFigurePhotography #JurassicWorld #JurassicPark #Raptors…,GueroVzn
2556,2019-03-16 20:40:01+00:00,Detroit,1107094203589365762,"There is a scene in Jurassic World fallen kingdom where Chris Pratt unleashes a pachycephalosaurus, and it runs around Headbutting people while the Indo-raptor is in the cage. I feel like the pachycephalosaurus would be more alarmed by the Indo-raptor",andy65226576
2855,2019-03-21 19:29:36+00:00,Brooklyn,1108888422297542656,Seriously the green zone is so lush I’m worried that @EllenPompeo is going to start fighting off raptors like it’s Jurassic Park #GreysAnatomy,writerly203
2865,2019-03-22 12:57:17+00:00,Los Angeles,1109152081703772161,Opening this Summer at @unistudios ! The T-Rex will now face a new behemoth dinosaur - a refreshed Raptor Encounter and Dino Play area will also launch. #jurassicworldtheride…,endorexpress
2938,2019-03-22 23:30:58+00:00,Detroit,1109311553172582401,Hey don’t get shitty about me spitting. I’m just trying to get casted as a spitting Raptor in the new @JurassicPark movie.,TheSamiCallihan
2950,2019-03-23 14:10:39+00:00,Los Angeles,1109532931515650055,#RavenclawPrideDay When the Wizarding World meets Jurassic World? Here I am with Raptor Blue while as the Head Boy of Ravenclaw. Blue was happy with my house colors and wanted to get a…,amartist17
2960,2019-03-23 18:55:28+00:00,New York,1109604607209156608,That Raptor monologue from Jurassic Park. I’d let that happen to me before allowing either of those jackasses back,HonorclubDan
3125,2019-03-26 14:33:41+00:00,Boston,1110625890197823494,"@Jared_Carrabis Velociraptors are the size of a chicken, but the Utahraptor is about the size of the raptors from Jurassic Park/World, so they do exist.",SammyJSammyJ
3127,2019-03-26 15:27:34+00:00,Dallas,1110639452085514242,Had an amazing time getting a private tour of Chronicle Collectables and got to see some props from my favorite movies... including this shouting match with the raptor from the original Jurassic Park.,JenMyersWeather
3220,2019-03-28 00:52:01+00:00,Orlando,1111143889149349888,"CW: Jurassic World: FK #spoilers For the record. It was thought in the Jurassic fandom that Rexy, Blue, or both would die in Fallen Kingdom. With the killing off of the other three raptors in the original film, it didnt seem too farfetched. I fuckin SOBBED when they both lived.",wooflecone
3495,2019-04-03 12:10:39+00:00,Los Angeles,1113488997773402115,Glad this question is finally answered . • • • • • #jurassicjen #jendurst ###jurassicgirl #raptor #dinostyle #dinosaurs #dino #trex #lifefindsaway #jurassicpark #humpday #jurassicfan…,thejurassicjen
3574,2019-04-04 14:38:20+00:00,New York,1113888551840747521,"Watching the Jurassic Park 3D re-release, when the raptor pops out from behind the electrical panel the lady in the row next to me jumped so hard she fell out of her seat.",toebone
3781,2019-04-07 17:54:44+00:00,Toronto,1115025142973964289,Last home game of the regulars ends FANAPALOOZA/EARLY START/OVERTIME STYLE! @raptors WIN! #raptors 117 #miami 109!Me @4KORNERS @MatterofKAT got more for you guys next week Next time we see you in #the6ix its #NBAPLAYOFFS #WeTheNorth #rtz #jurassicpark ALL THAT! #lovemyjob,strizzzy
3847,2019-04-09 12:02:38+00:00,Los Angeles,1115661310128160774,It’s really too hot for a blanket today but oh well ! #representing • • • • • #jurassicjen #jendurst ###jurassicgirl #raptor #dinostyle #dinosaurs #dino #trex…,thejurassicjen
3907,2019-04-10 13:04:27+00:00,Sacramento,1116039253182623744,Who says dinosaurs went extinct...?! Someone better call Jurassic Park ‘cause there’s a Raptor on the loose Hard work and Dedication pays off …,gagebort
3919,2019-04-10 18:38:59+00:00,San Francisco,1116123441935994880,You need a meme clip of moldune (probably misspelled) from Jurassic park #1 when he gets eaten by the raptor.,JSRW1986

In [20]:
remove_query('jurassic')

In [21]:
raptors[raptors['Tweet'].str.contains('soccer', case=False)]

,Date,Game Location,ID,Tweet,User
822,2018-10-10 17:03:12+00:00,Philadelphia,1050144744565694464,We fought out a good mid-week 2-1 win over Lancaster Bible @rutgers_camden d3soccer @RUC_Raptors #ncaa #college #collegesoccer #rutgers #camden #rutgerscamden #ruc #camdennj #nj #newjersey…,rucms
841,2018-10-15 20:06:00+00:00,Philadelphia,1052002687368060928,Assistant Coach @mikeryan93 went from all time leading goal scorer to Goalkeeper tonight at training @rutgers_camden d3soccer @RUC_Raptors #ncaa #college #collegesoccer #rutgers #camden…,rucms
842,2018-10-16 09:24:50+00:00,Philadelphia,1052203721868959745,#Repost d3soccer ・・・ POLL | We are receiving votes in the week 7 edition of the national rankings @rutgers_camden @RUC_Raptors @njacsports @Rutgers University—Camden,rucms
916,2018-10-20 07:45:48+00:00,Philadelphia,1053628350827298816,It’s MATCHDAY! We are back at home as we take on @wpusoccer today in a 1pm kickoff @rutgers_camden d3soccer @njacsports @RUC_Raptors #ncaa #college #collegesoccer #rutgers #camden…,rucms
920,2018-10-20 12:26:53+00:00,Philadelphia,1053699087084613632,Our Starting XI is on the field... @rutgers_camden @njacsports d3soccer @RUC_Raptors rutgerscamdenalumni #ncaa #college #collegesoccer #rutgers #camden #rutgerscamden #ruc #camdennj #nj…,rucms
925,2018-10-20 14:59:20+00:00,Philadelphia,1053737452979003400,"And that’s it, we are back on the mark with a big win to go 5-2-1 in conference @rutgers_camden @njacsports d3soccer @RUC_Raptors rutgerscamdenalumni #ncaa #college #collegesoccer…",rucms
971,2018-10-24 07:48:39+00:00,Philadelphia,1055078617334644737,It’s MATCHDAY! We head down to Pomona for the regular season finale to take on @stocktonospreys for a 7:30pm kickoff @rutgers_camden d3soccer @RUC_Raptors @njacsports #ncaa #college…,rucms
973,2018-10-24 11:43:52+00:00,Philadelphia,1055137810129272832,#Repost d3soccer ・・・ POLL | We are receiving votes in the week 8 edition of the national rankings @rutgers_camden @RUC_Raptors @njacsports @Rutgers University—Camden,rucms
999,2018-10-25 07:43:19+00:00,Philadelphia,1055439663828103169,"After our win and the other results last night, the final @njacsports Men’s Soccer Standings look like this... @rutgers_camden d3soccer @RUC_Raptors rutgerscamdenalumni #ncaa #college…",rucms
1000,2018-10-25 07:50:07+00:00,Philadelphia,1055441373212631041,"After our win and the other results last night, the final @njacsports Men’s Soccer standings look like this; @rutgers_camden d3soccer @RUC_Raptors rutgerscamdenalumni #ncaa #college…",rucms
1033,2018-10-27 06:58:35+00:00,Philadelphia,1056153179522457600,It’s MATCHDAY! We open up the @njacsports Men’s Soccer Championship back at home as the #3 seed taking on #6 @wpusoccer today in a 12pm kick off. @rutgers_camden d3soccer @RUC_Raptors…,rucms
1040,2018-10-27 15:24:32+00:00,Philadelphia,1056280509171617793,Well that didn’t go as planned!? But we don’t expect to be done for the year. We’ll be back at it @rutgers_camden d3soccer @RUC_Raptors #ncaa #college #collegesoccer #rutgers #camden…,rucms
1066,2018-10-30 06:41:12+00:00,Philadelphia,1057235970985091072,We may not be playing but today’s matches could have a big impact on our chances to advance to the NCAA tournament @rutgers_camden d3soccer @RUC_Raptors @njacsports rutgerscamdenalumni…,rucms
1090,2018-11-02 17:27:14+00:00,Philadelphia,1058485714168569856,"The @njacsports Final kicks off shortly. We missed out this year but we will be watching, will you? LIVE VIDEO: @rutgers_camden d3soccer @RUC_Raptors…",rucms
1091,2018-11-02 18:39:58+00:00,Philadelphia,1058504015791689728,Watching the @njacsports Men’s Soccer Final as team... 30’ MSU 1 - RCNJ 0 LIVE VIDEO: @rutgers_camden d3soccer @RUC_Raptors rutgerscamdenalumni #ncaa #college…,rucms
1137,2018-11-10 16:31:10+00:00,Philadelphia,1061370705470603264,"With our win today, we advance to play @wpusoccer tomorrow at 12pm @rutgers_camden d3soccer @njacsports @RUC_Raptors rutgerscamdenalumni #ncaa #college #collegesoccer #rutgers #camden…",rucms
1144,2018-11-11 19:31:10+00:00,Philadelphia,1061778394029977601,Our 2018 season ended today after our loss in the Quarterfinals of the @ecacsports DIII Men’s Soccer Championship @rutgers_camden @njacsports d3soccer @RUC_Raptors #ncaa #college…,rucms
1233,2018-11-22 16:55:04+00:00,Philadelphia,1065725375832104960,Happy Thanksgiving from everyone at @rutgers_camden Men’s Soccer! @RUC_Raptors @Rutgers University—Camden,rucms
1300,2018-11-28 10:04:31+00:00,Washington D.C.,1067796384785539074,Congratulations to our #MC_Raptors men’s soccer All Conference and NJCAA DI All Region award recipients! Youness Benmouna All-MD JUCO First Team and All-Region First Team Daniel Juresic…,MC_Raptors
1301,2018-11-28 10:20:15+00:00,Washington D.C.,1067800342497251328,Congratulations to our #MC_Raptors women’s soccer All Conference and NJCAA DI All Region award recipients! Ariella Amaguana All-MD JUCO First Team and All-Region First Team Viviana…,MC_Raptors
1434,2018-12-10 18:10:48+00:00,Philadelphia,1072267415277457408,"#Congratulations to James Brett, for being named @UnitedCoaches 2nd Team All-South Atlantic Region @rutgers_camden d3soccer @RUC_Raptors @njacsports rutgerscamdenalumni #ncaa #college…",rucms
2119,2019-02-25 18:38:25+00:00,Toronto,1100178230194126848,Big boy can move . . gtasportsplex . . #basketball #bucks #nba #ballers #strong #dancemoves #raptors #the6 #sports #fans #playoffs #soccer #hockey #tradedeadline #volleyball #fun…,vaughansports

In [22]:
remove_query('soccer')

In [23]:
raptors[raptors['Tweet'].str.contains('Lazer Raptor', case=False)]

,Date,Game Location,ID,Tweet,User
1471,2018-12-14 21:09:23+00:00,Indianapolis,1073761910284267525,Drinking a Lazer Raptor by @CSBrewing at @thekoelschip —,jsg1965
1479,2018-12-15 21:03:02+00:00,Indianapolis,1074122701453836288,Well executed if this is what you want. Flavor and finish disagrees with my soul is all. - Drinking a Lazer Raptor by @CSBrewing at @kumasindy —,BigEyedFisch
1489,2018-12-17 18:47:02+00:00,Indianapolis,1074813250628448256,It’s cranberry season!! -DC - Drinking a Lazer Raptor by @CSBrewing at @TomTapRoom —,coltscouchcrew
1532,2018-12-22 21:17:04+00:00,Indianapolis,1076662948024721409,Drinking a Lazer Raptor by @CSBrewing @Personal’s Pubhouse —,PersonalOwn4g3
1724,2019-01-11 20:59:10+00:00,Indianapolis,1083906200348082177,Central State Lazer Raptor on tap now. @CSBrewing @TheAleEmporium #BeerMenus,TheAleEmporium
1770,2019-01-16 21:15:09+00:00,Cleveland,1085722162017775616,Drinking a Lazer Raptor by @CSBrewing @The Trap House —,sam_see
1829,2019-01-22 13:47:30+00:00,Chicago,1087783832567336960,Central State Lazer Raptor on tap now. @CSBrewing @rpublichouse #BeerMenus,rpublichouse
1872,2019-01-26 21:57:05+00:00,San Francisco,1089356592921931782,Drinking a Lazer Raptor by @CSBrewing @City of Walnut Creek —,LordMounce
1874,2019-01-27 10:16:02+00:00,Chicago,1089542556189380608,Drinking a Lazer Raptor by @CSBrewing at @bangersandlace —,carlosveiolima
1911,2019-02-01 21:46:09+00:00,Miami,1091528168652054528,Drinking a Lazer Raptor by @CSBrewing at @boxeldermiami —,Jeyrod11
1951,2019-02-05 21:32:02+00:00,Brooklyn,1092974167484436482,Drinking a Lazer Raptor by @CSBrewing at @covenhovennyc —,BeeryHott
1979,2019-02-09 02:33:06+00:00,Chicago,1094137098364428288,Central State Lazer Raptor on tap now. @CSBrewing #BeerMenus,ParlorChicago
2042,2019-02-14 21:28:00+00:00,Brooklyn,1096234643085512704,Drinking a Lazer Raptor by @CSBrewing @City Hops —,robspc
2160,2019-03-01 21:04:06+00:00,Cleveland,1101664445544218625,Not bad! - Drinking a Lazer Raptor by @CSBrewing at @roziswinehouse —,donnheck

In [24]:
remove_query('Lazer Raptor')

In [25]:
raptors[raptors['Tweet'].str.contains('Laser Raptor', case=False)]

,Date,Game Location,ID,Tweet,User
824,2018-10-11 13:25:03+00:00,Chicago,1050452233110863873,Tentative Draft Line-Up These are all subject to change (but things are looking pretty insane.) • American Solera - Goodberry American Solera - Magic Jar Aslin - Laser Raptors Aslin -…,TheBeerTemple
835,2018-10-15 15:37:50+00:00,Washington D.C.,1051935200396136450,Drinking a Laser Raptors by @Aslin_BeerCo @Washington &amp; Old Dominion Trail —,retractedwords
1974,2019-02-08 00:28:02+00:00,Washington D.C.,1093743232650014720,Drinking a Laser Raptors by @Aslin_BeerCo at @safeway —,LoTGoD

In [26]:
remove_query('Laser Raptor')

In [27]:
raptors[raptors['Tweet'].str.contains('encounter', case=False)]

,Date,Game Location,ID,Tweet,User
981,2018-10-24 18:24:47+00:00,Orlando,1055238707538739200,Got to meet Blue! She’s......nice #JP @Raptor Encounter,magicfergie
1060,2018-10-29 17:03:02+00:00,Orlando,1057030072987799553,First Mate and I met Blue! She even gave me a friendly nudge. (Just look at his sweet face). @Raptor Encounter,pattyjrobinson
1063,2018-10-29 18:49:29+00:00,Orlando,1057056858966499329,Working on those knock knock jokes while we wait to meet Blue the Raptor. @Raptor Encounter,pattyjrobinson
1095,2018-11-03 12:14:05+00:00,Orlando,1058769293498699777,#uoap #kasenetz @Raptor Encounter,dkasenetz
1187,2018-11-15 19:54:30+00:00,Orlando,1063233815391453184,#raptorencounter en Raptor Encounter,jotitaazul
1193,2018-11-16 12:35:29+00:00,Orlando,1063485721586122752,This video always makes me laugh! (raptor tried to get fresh tho!) #RealFear @Raptor Encounter,ShaneYambor
1203,2018-11-17 10:03:05+00:00,Orlando,1063809758975660033,"(@Raptor Encounter in Orlando, FL)",AnonadadoAr
1232,2018-11-22 11:46:17+00:00,Orlando,1065647666472701954,I said YES! Engaged to Blue. @Raptor Encounter,f3rnandoza
1310,2018-11-29 10:43:44+00:00,Orlando,1068168641152237569,"I'm at Raptor Encounter in Orlando, FL",OLSinFLA
1338,2018-12-01 13:40:26+00:00,Orlando,1068937887062872064,"I'm sure Jack would deny being a little scared, but his body language tells another story. Lily had the right idea: stay far away! @Raptor Encounter",heatherwassing
1655,2019-01-08 00:57:46+00:00,Orlando,1082516693702852610,Happy 33rd Anniversary to my amazing parents. They’ve given me everything I always needed and wanted and so much more than I can ever thank them for. I love you guys. @Raptor Encounter,KristiLuWh0
1657,2019-01-08 12:20:22+00:00,Orlando,1082688476758331392,Islands of adventure!! #park #amusement @Raptor Encounter,YogaGirlMich
1714,2019-01-11 16:38:31+00:00,Orlando,1083840604616814592,This was fun @Raptor Encounter,ar_hope
1759,2019-01-15 16:56:00+00:00,Orlando,1085294554373337088,It looks so real! @Raptor Encounter,Rodmarcus
1783,2019-01-17 12:45:57+00:00,Orlando,1085956403523735552,#kalsongbyte @Raptor Encounter,kurkkio
1912,2019-02-02 00:56:47+00:00,Orlando,1091576141113184256,em Raptor Encounter,alannuguette
2057,2019-02-18 19:10:05+00:00,Orlando,1097649484476108800,:) en Raptor Encounter,nopiedra
2058,2019-02-19 01:53:08+00:00,Orlando,1097750918567583745,Dino shot! @Raptor Encounter,ColinB75
2061,2019-02-19 13:29:08+00:00,Orlando,1097926072455319553,"You're my boy, Blue!!! @Raptor Encounter",TBAH_Ryan
2066,2019-02-20 19:03:20+00:00,Los Angeles,1098372565100183553,We finally got to meet Blue today @Raptor Encounter,_emiforever_
2226,2019-03-09 16:53:25+00:00,Orlando,1104500463200862210,Yea we basically made out @Raptor Encounter,AlvinLeonel
3121,2019-03-26 13:03:17+00:00,Orlando,1110603139848249345,Got some VIP treatment at Raptor Encounter today. Met this queen. I aspire to be her everyday. @Raptor Encounter,magicalandgay
3232,2019-03-28 14:00:57+00:00,Los Angeles,1111342427632095232,The New Raptor Encounter Photo: @chefraz83 on IG,Ben_Conw
3384,2019-03-31 08:44:13+00:00,Philadelphia,1112349885356036098,"I know Lowe and other media talk about Raptors fans storming the gates and I have a much, much smaller interaction rate, but Toronto fans I've encountered have always engaged in conversation vs. angry tribalism. Again, small/biased sample.",_JimmyMcCormick

In [28]:
remove_query('encounter')

In [29]:
raptors[raptors['Tweet'].str.contains('adventures', case=False)]

,Date,Game Location,ID,Tweet,User
819,2018-10-10 09:53:25+00:00,Orlando,1050036587801833472,"Meeting Trezos was AWESOME Check out our YouTube channel ""Raptor Adventures ""to see our Gatorland Vlog @Gatorland Orlando",RAPtorENTMusic
1360,2018-12-04 06:45:53+00:00,Toronto,1069920724377329665,My beau-pere adventures at a Raptors game. #AnJolaAdventures #wethenorth #raptorsgame #raptorsbasketball #family #familyvillage @Scotiabank Arena,almohonu
1845,2019-01-23 15:18:09+00:00,New York,1088169032782626816,"We had 12 hours in New York....check out our YouTube channel Raptor Adventures to see Our New York Minute with Original Music by our group RAPtor ENT @New York, New York",RAPtorENTMusic
3809,2019-04-08 09:50:05+00:00,Washington D.C.,1115265562152701954,This Bison was one of the highlights roers_zoofari Check out the vlog...it's pretty awesome. The link is in our Bio or you can just google Raptor Adventures and search for our most…,RAPtorAdventur1

In [30]:
remove_query('adventures')

In [31]:
raptors[raptors['Tweet'].str.contains('exposure', case=False)]

,Date,Game Location,ID,Tweet,User
1037,2018-10-27 13:20:18+00:00,Los Angeles,1056249245500608512,Boys 9U - Pool A - Burbank Raptors def. Mavericks Legacy 30-7 @exposurebball,socalbuzzbball
1038,2018-10-27 14:29:58+00:00,Los Angeles,1056266775644590080,Boys 8u - Pool B - Burbank Raptors def. Mavericks Legacy 25-4 @exposurebball,socalbuzzbball
1039,2018-10-27 15:10:07+00:00,Los Angeles,1056276881627140096,Boys 9U - Pool A - Squad def. Burbank Raptors 25-23 @exposurebball,socalbuzzbball
1041,2018-10-27 16:40:01+00:00,Los Angeles,1056299505098854400,Boys 8u - Pool B - A-Team Basketball 8U def. Burbank Raptors 19-14 @exposurebball,socalbuzzbball
1042,2018-10-27 17:49:51+00:00,Los Angeles,1056317076632190976,Boys 12U - Pool A - A-Team Basketball 12U def. Burbank Raptors 37-19 @exposurebball,socalbuzzbball
1044,2018-10-27 19:49:57+00:00,Los Angeles,1056347301063651328,Boys 12U - Pool A - Whitter Bulldogs def. Burbank Raptors 39-34 @exposurebball,socalbuzzbball
1046,2018-10-28 11:00:00+00:00,Los Angeles,1056576324532363264,Boys 9U - Championship (G1) - Burbank Raptors def. Mavericks Legacy 28-11 @exposurebball,socalbuzzbball
1047,2018-10-28 12:10:22+00:00,Los Angeles,1056594033307475969,Boys 8u - Championship (G3) - Squad def. Burbank Raptors 15-6 @exposurebball,socalbuzzbball
1049,2018-10-28 13:39:51+00:00,Los Angeles,1056616552840265730,Boys 9U - Championship (G2) - Squad def. Burbank Raptors 15-6 @exposurebball,socalbuzzbball
1867,2019-01-26 11:59:58+00:00,Oklahoma City,1089206320899735553,6th Grade Boys - Pool A - Raptors def. OK Swish White League 45-14 @exposurebball,soirelandbball
1868,2019-01-26 12:59:55+00:00,Oklahoma City,1089221408792739840,6th Grade Boys - Pool A - Raptors def. Tuttle Elite 40-27 @exposurebball,soirelandbball
2159,2019-03-01 20:34:53+00:00,Orlando,1101657093193510912,11th/12th Grade Boys D2 - Pool A - Raptors Elite def. Team Evolution 42-39 #basketball @exposurebball,TheSuper6Series
2173,2019-03-02 20:54:59+00:00,Orlando,1102024541423824897,11th/12th Grade Boys D2 - Pool A - Raptors Elite def. Chobe Kings 43-42 #basketball @exposurebball,TheSuper6Series
2181,2019-03-03 17:34:53+00:00,San Antonio,1102336571062317061,BOYS 7th Grade - Pool A - Elite Spurs (Martinez) def. SA Select Raptors (Jones) 43-32 @exposurebball,ACATexas
2185,2019-03-03 17:59:52+00:00,Orlando,1102342857321562113,11th/12th Grade Boys D2 - Championship (G2) - Raptors Elite def. Rome Athletics 42-37 #basketball @exposurebball,TheSuper6Series
2189,2019-03-03 19:04:52+00:00,San Antonio,1102359216935890945,BOYS 7th Grade - Pool A - SA Select Raptors (Jones) def. TX Bad Boys (Hale) 42-35 @exposurebball,ACATexas
2191,2019-03-03 20:14:50+00:00,Orlando,1102376824686985217,11th/12th Grade Boys D2 - Championship (G5) - Orlando Bad Boys def. Raptors Elite 45-42 #basketball @exposurebball,TheSuper6Series
2193,2019-03-03 21:29:51+00:00,San Antonio,1102395702754373633,BOYS 7th Grade - Pool A - Pleasanton Eagles (Moos) def. SA Select Raptors (Jones) 47-39 @exposurebball,ACATexas
2537,2019-03-16 12:15:02+00:00,San Antonio,1106967121513324550,BOYS 7th Grade - Pool A - SA Select Raptors (De Jones) def. SA Dream (Simpson) 47-42 @exposurebball,ACATexas
2538,2019-03-16 12:15:10+00:00,Houston,1106967151569719296,VARSITY GIRLS - Pool E - BDA def. RICE RAPTORS (LEGACY) 42-19 @exposurebball,bballnation13
2546,2019-03-16 15:20:01+00:00,Houston,1107013671996268544,VARSITY GIRLS - Pool E - RICE RAPTORS (LEGACY) def. LADY HEAT 53-46 @exposurebball,bballnation13
2547,2019-03-16 16:04:57+00:00,San Antonio,1107024979974152193,BOYS 7th Grade - Pool A - TX Tribe (Rizo) def. SA Select Raptors (De Jones) 47-28 @exposurebball,ACATexas
2566,2019-03-17 11:04:54+00:00,San Antonio,1107311859076661248,BOYS Junior Varsity - Brackets (G3) - SA Outlaws (Estes) def. SA Select Raptors-2022 (De Jones) 44-13 @exposurebball,ACATexas
2570,2019-03-17 12:59:51+00:00,San Antonio,1107340786201440256,BOYS Junior Varsity - Brackets (G8) - Mas Dreamers (Ayad) def. SA Select Raptors-2022 (De Jones) 61-41 @exposurebball,ACATexas
2641,2019-03-18 14:21:54+00:00,San Antonio,1107723822873096192,GIRLS HS - Open - Pool A - SA Hustlers (Seaton) def. SA Select Raptors (De Jones) 39-17 @exposurebball,ACATexas
2944,2019-03-23 09:34:57+00:00,San Antonio,1109463549573849089,15U - Pool A - SA Hoops Elite 2022 def. SA Select Raptors 78-18 - Gunner Goff leads the way w/16pts in the win @exposurebball,AlamoCityHoops1
2949,2019-03-23 13:05:07+00:00,San Antonio,1109516437696274434,15U - Pool A - 360 Elite -Burris def. SA Select Raptors 65-32 - Joshua Glasco of Blooming Gove goes for 21pts in the win @exposurebball,AlamoCityHoops1
2956,2019-03-23 16:20:14+00:00,San Antonio,1109565540052451328,15U - Pool A - SA 44 def. SA Select Raptors 64-45 - Jalon Munoz (2023) again leading the way w/18pts &amp; hitting on 2 treys @exposurebball,AlamoCityHoops1
2972,2019-03-24 11:50:01+00:00,San Antonio,1109859927399587840,15U - Pool A - Texas Tigers def. SA Select Raptors 63-33 @exposurebball,AlamoCityHoops1
3321,2019-03-30 15:49:52+00:00,Houston,1112094615388209152,Middle School Boys - Pool AA - Katy Raptors - Blanchard def. Ankle Breakers 38-12 #bigtimehoopsdmv @exposurebball,bigtimehoopsDMV
3387,2019-03-31 10:25:08+00:00,Houston,1112375281979924480,Middle School Boys - Championship (G2) - Katy Raptors - Kingsley def. Ankle Breakers 52-24 #bigtimehoopsdmv @exposurebball,bigtimehoopsDMV
3389,2019-03-31 11:59:55+00:00,Houston,1112399133241946113,Middle School Boys - Championship (G3) - BIG Basketball Academy Hurricanes White def. Katy Raptors - Kingsley 63-40 #bigtimehoopsdmv @exposurebball,bigtimehoopsDMV
3393,2019-03-31 13:15:05+00:00,Houston,1112418050500898816,Middle School Boys - Championship (G4) - SWAG Elite def. Katy Raptors - Blanchard 52-49 #bigtimehoopsdmv @exposurebball,bigtimehoopsDMV
3658,2019-04-06 10:10:04+00:00,Houston,1114545814293053441,13U Boys - Pool B - Katy Raptors - Kingsley def. Houston Kingz 52-22 #OFFDAHOOK @exposurebball,BrianJolivette
3661,2019-04-06 11:24:57+00:00,Houston,1114564659439382528,12U Boys - Pool A - Katy Raptors 2025 def. Brazos Valley Elite 50-41 #OFFDAHOOK @exposurebball,BrianJolivette
3664,2019-04-06 13:09:52+00:00,Houston,1114591065338724352,15U Boys - Pool A - BBA def. Katy Raptors 2022 74-60 #OFFDAHOOK @exposurebball,BrianJolivette
3666,2019-04-06 13:45:14+00:00,Houston,1114599964997488640,13U Boys - Pool B - Katy Raptors - Kingsley def. Houston Fastbreakers 57-17 #OFFDAHOOK @exposurebball,BrianJolivette
3698,2019-04-07 09:04:56+00:00,Houston,1114891811967983617,15U Boys - Championship (G4) - Katy Raptors 2022 def. Houston Topguns 71-58 #OFFDAHOOK @exposurebball,BrianJolivette
3721,2019-04-07 11:35:20+00:00,Houston,1114929662768156672,13U Boys - Championship (G2) - Katy Raptors - Blanchard def. Scholar Athletes HL (13u) 50-46 #OFFDAHOOK @exposurebball,BrianJolivette
3728,2019-04-07 12:10:04+00:00,Houston,1114938402506461184,12U Boys - Championship (G3) - Katy Raptors 2025 def. Team Fox 51-37 #OFFDAHOOK @exposurebball,BrianJolivette
3765,2019-04-07 14:15:17+00:00,Houston,1114969914144694272,13U Boys - Championship (G4) - Katy Raptors - Kingsley def. Houston Flight-BLUE 44-37 #OFFDAHOOK @exposurebball,BrianJolivette
3766,2019-04-07 14:15:19+00:00,Houston,1114969921283403779,12U Boys - Championship (G7) - HTown Finest def. Katy Raptors 2025 44-33 #OFFDAHOOK @exposurebball,BrianJolivette
3784,2019-04-07 18:59:55+00:00,Houston,1115041547207217154,13U Boys - Championship (G6) - Katy Raptors - Kingsley def. Katy Raptors - Blanchard 75-51 #OFFDAHOOK @exposurebball,BrianJolivette
3785,2019-04-07 18:59:56+00:00,Houston,1115041547790237698,Congratulations to Katy Raptors - Kingsley! OFF DA HOOK 13U Boys Champions #OFFDAHOOK @exposurebball,BrianJolivette
3789,2019-04-07 19:14:55+00:00,Houston,1115045319081902081,15U Boys - Championship (G7) - Katy Select (Ransom) def. Katy Raptors 2022 59-57 #OFFDAHOOK @exposurebball,BrianJolivette

In [32]:
remove_query('exposure')

In [33]:
raptors[raptors['Tweet'].str.contains('halloween', case=False)]

,Date,Game Location,ID,Tweet,User
1036,2018-10-27 12:45:51+00:00,Orlando,1056240575693893632,Dinosaur races at the victorymaocoee Halloween party!! #victorymartialarts #teamocoee #dinosaurs #raptor #trex #halloweencostume #halloween #tkd #martialarts @Victory Martial Arts,DJTremz
1078,2018-10-31 10:27:50+00:00,Toronto,1057655393801957376,The #halloween episode of the 'Macko &amp; Cauz' Podcast will be out a little later today. parkdalepanther gives his Top-5 Halloween Heroes. + plenty of #Raptors and #austonmatthews…,mcauz56
1081,2018-10-31 20:16:14+00:00,Los Angeles,1057803466834239488,Just landed in #fortnitemares as #raptor ready to farm some #candy #cosplay #halloweencostume #happyhalloween @fortnitegame epic @ninja @sypherpk pokimanelol @nickmercs @joelmchale…,AaronIkeda
1082,2018-10-31 22:41:14+00:00,Toronto,1057839957333762048,#Raptors appeared in Wellesley subway station! #happyhalloween @Church and Wellesley,SimonWYHuang
1086,2018-11-02 13:27:16+00:00,Minneapolis,1058425324449525760,I had maybe TOO much fun with The Raptor Center’s Facebook Live event this Halloween- Nero the Turkey Vulture got his food in a pumpkin! Check out the video on The Raptor Center’s…,KaylaJoW

In [34]:
remove_query('halloween')

In [35]:
raptors[raptors['Tweet'].str.contains('little raptors', case=False)]

,Date,Game Location,ID,Tweet,User
1110,2018-11-05 16:51:29+00:00,Chicago,1059563878600925184,"More cosplay photos coming soon from Youmacon, but for now, I'm just happy to be home with these little raptors @Chicago, Illinois",Etaru

In [36]:
remove_query('little raptors')

In [37]:
raptors[raptors['Tweet'].str.contains('vertimax', case=False)]

,Date,Game Location,ID,Tweet,User
1216,2018-11-20 12:30:24+00:00,Philadelphia,1064933994872127489,matthew_lopez35 back from his season in Paraguay using the @vertimax raptor trying to game to the NE T level for his season in Puerto Rico! vertimaxbasketball and the #TrustTheProcess…,EdDueces

In [38]:
remove_query('vertimax')

In [39]:
raptors[raptors['Tweet'].str.contains('bird', case=False)]

,Date,Game Location,ID,Tweet,User
1143,2018-11-10 22:24:30+00:00,San Francisco,1061459628096012288,"Predator #hawkeye #hawkeyes #hawk #raptors #raptorlife #birdsofprey #birdshots #naturephotography #nature_shots #nature_lovers @Lower Haight, San Francisco",davidwfloydart
1192,2018-11-16 12:05:06+00:00,Denver,1063478076917583873,I read over at natgeoyourshot that 2018 is being designated Year of the Bird. #redtailedhawk #raptor #birdofprey #dinosaur @Waverly Acres Park,kylermedina
1223,2018-11-21 11:40:56+00:00,Orlando,1065283934920032264,Contemplative red shouldered hawk #florida #fl #birds #wetlands #parks #outdoors #hawks #birdsofprey #birdsofinsta #birdstagram #raptors #redshoulderedhawk #apopka #centralflorida…,gspeed0689
1439,2018-12-11 18:18:50+00:00,Los Angeles,1072631824453656576,"You never know who or what you will meet in Compton...#comptonstories #raptors #urbanwildlife #urbanraptors #urbanbirdsofprey #birdsofprey @Compton, California",winegrrl
1552,2018-12-27 12:15:17+00:00,Toronto,1078338540709138432,"The Bird enjoying her FREE medium fries - only in the My McD’s app. Thanks Raptors! @Toronto, Ontario",skripper
1554,2018-12-28 15:43:43+00:00,Orlando,1078753383656214528,Osprey carrying away a catch. #osprey #birdofprey #birdofpreyphotography #only_raptors #only_raptors_inflight #lakeapopka #wintergarden #wintergardenfl #wintergardenflorida #bird_captures…,JMBurket
1614,2019-01-04 13:24:41+00:00,Orlando,1081255111421243392,Awe yeah! #birdsofprey #raptors #fourleafclover #ilovemaitland #lovewhereyoulive @maitlandlife remone_gildemeister @Audubon Center for Birds of Prey,joseph_rasch
1711,2019-01-11 15:09:34+00:00,Orlando,1083818217754177536,From the series “AVERY’S OWLS” #owl #owlsofinstagram #birds #birdsofinstagram #birdsofprey #raptors #waycoolshots #animal #instaowl #HowIRoam #wildlifephotography #wildlife #wild…,ElianaWolf2
1712,2019-01-11 15:09:41+00:00,Orlando,1083818249085771776,"From the series ""THE RAPTORS"" #instabird #birds #birdsofinstagram #usa #waycoolshots #birdie #pocket_birds #waycoolshots #exploretocreate #wildlife #animals #birdphotography…",ElianaWolf2
1826,2019-01-22 00:35:05+00:00,Los Angeles,1087584414861803521,Red Tailed Hawk - Locked and Loaded #elite_raptors #kings_birds #birdsofprey #birdsinflight #redtailedhawk #wildlifephotography #natgeoyourshot #natureshot #birdstagram #birdphotography…,J007_
1859,2019-01-25 15:53:04+00:00,Los Angeles,1088902598013435904,Osprey at full stretch #osprey #elite_raptors #elite_worldwide_birds #wildlifephotography #birdfreaks #birdsofprey #birdsinflight #igers #tamron150600mm #NikonD810 #nikonfullframe…,J007_
1871,2019-01-26 17:30:09+00:00,Chicago,1089289417724968961,Caught an American Kestrel on his lunch break in downtown Chicago. I think he had a sparrow. #chicago #kestrel #raptor #birdofprey #bird #animals #nature #savage #circleoflife #chicago…,HughMSullivan
1893,2019-01-30 22:21:43+00:00,Orlando,1090812340835180545,"Great Horned Owl in Oakland, FL. #owl #owls #owlsofinstagram #owlnest #raptors #nikoncoolpixp900 #birdnest #only_raptors #elite_raptors #bestbirds #birdwatching #bestbirdshots #natureza …",JMBurket
2020,2019-02-12 12:34:56+00:00,New York,1095375714793209856,"Saw nature surviving today's Winter storm. This raptor had a bird for lunch. #urbannature #raptor #maplewoodnj #natureinthecity #urbanbirder #NJraptor #hawk @Maplewood, New Jersey",WhereIsJaneMyra
2025,2019-02-13 18:47:05+00:00,Brooklyn,1095831759365787649,Two lovebirds a day early. #birdcp #lovebirds #raptors #valentines #hawk #centralpark @The Ramble,The_GreatAuk
2051,2019-02-16 15:14:43+00:00,Phoenix,1096865480227221504,"Allow me to introduce Eric and his pal, Norman Bates, a Harris hawk, who keeps pesty birds (like grackles) away from guests here in Arizona. #falconeer #raptor #birdsofprey #prettybird…",fuelthefiretv
2110,2019-02-24 18:06:51+00:00,Los Angeles,1099807898912182272,"Whattup homie? #hawk #raptor #prospectivefalconer #birdnerd #californiahawkingclub #spiritanimal #messenger #wildlife @Los Angeles, California",thesvh
2219,2019-03-07 22:57:49+00:00,Minneapolis,1103867392801697793,#uofm #raptorcenter #fun #onlyinmn #eagles #owls #hawks #falcons #vulture #birdnerd #birdy #brody #birdlover @The Raptor Center,Pauly_ccrider
2293,2019-03-11 12:20:07+00:00,Brooklyn,1105156458293923840,"I started being interested in identifying local raptors in 2009 when I started volunteering at a wildlife refuge with unreleasable birds of prey, but my first eBird list is from a trip to Maine in 2011 where I saw loons, cormorants and my first Atlantic puffin :) so 10ish years!",mollycule__
2297,2019-03-11 16:20:46+00:00,Sacramento,1105217021304659969,"Wildlife & Exotic Animal Symposium at UCD. It was a wonderful experience. I am still learning from the best. Dr. Duerr from the International Bird Rescue Center, Dr. Jonna Mazet from the One Health Institute and my mentor Dr. Michelle Hawkins from the California Raptor Center. – at Valley Hall",CharleneLujanV
2391,2019-03-12 19:56:28+00:00,Denver,1105633691668107264,Omg I love birds of prey I have books on books of them sksk shout out to all the raptors!!,TheOfficialChe
2563,2019-03-17 08:35:04+00:00,Toronto,1107274152346615808,Red-tailed hawk from yesterday @downsviewpark . One of the top places in the city to see #Raptors #birding #Hawks #birdwatching #torontobirds,peterdwhitmore
2634,2019-03-18 12:33:28+00:00,Phoenix,1107696536517922816,"I hate to say this, but Lin's game and the Raptors' half-court offensive schemes are about as compatible as Larry Bird was compatible with Bill Laimbeer..... Lin will likely break out either under a different team or a different coach. (I really, really hope I'm wrong.)",ToddKrieger1
2957,2019-03-23 17:55:14+00:00,New York,1109589447434268673,"RED-TAIL HAWK Scanning for prey, and spinning his head left to right! @BirdQueens #REDTAILHAWK #bird_adored #elite_raptors #elite_owls #owl_guru #ethicalowlphotos #birdsofprey #oiseauxdeproie #birdwatching #wildlifephotography #WildlifeRefuge #raptors_only – at Stillwell Park",kikiscamera
2987,2019-03-24 17:26:59+00:00,Brooklyn,1109944726818557955,Look who decided to came out to say a Hello!!! OWLET next to his mama Great Horned Owl @BirdQueens #GreatHornedOwl #OWL2019 #owlet #bird_adored #elite_raptors #elite_owls #owl_guru #ethicalowlphotos #birdsofprey #chouetterayee #oiseauxdeproie – at Hempstead Lake State Park,kikiscamera
2989,2019-03-24 17:42:14+00:00,Brooklyn,1109948563348430848,"Mama Great Horned Owl feeding, and giving some love to here OWLET @BirdQueens #GreatHornedOwl #bird_adored #elite_raptors #elite_owls #owl_guru #ethicalowlphotos #birdsofprey #chouetterayee #oiseauxdeproie #oiseaux #wildlifephotography #Raptors #Birding – at Hempstead Lake State Park",kikiscamera
3323,2019-03-30 16:21:08+00:00,Washington D.C.,1112102482577113088,The Altamont Pass wind farm in California kills raptors every day. The Santa Barbara oil spill killed some birds 40 years ago. Your dissonance is quite stunning.,Tony__Heller
3365,2019-03-30 22:04:22+00:00,Brooklyn,1112188862309302273,The baby OWLETS were left alone under the watchful eye of Mama Great Horned Owl. @BirdQueens #GreatHornedOwl #bird_adored #elite_raptors #elite_owls #owl_guru #ethicalowlphotos #birdsofprey #chouetterayee #oiseauxdeproie #oiseaux #wildlifephotography #Raptors #Birding – at Hempstead Lake State Park,kikiscamera
3367,2019-03-30 22:14:32+00:00,Brooklyn,1112191420453060609,"Mama Great Horned Owl, ready to jump for the safety of here OWLETS! @BirdQueens #GreatHornedOwl #bird_adored #elite_raptors #elite_owls #owl_guru #ethicalowlphotos #birdsofprey #chouetterayee #oiseauxdeproie #oiseaux #wildlifephotography #Raptors – at Hempstead Lake State Park",kikiscamera
3422,2019-04-01 16:42:41+00:00,Toronto,1112832680058605584,"When did it become #MarchMadness ? Bird v. Magic, baby. Should the #Raptors go in the tank for a game or two in order to face Brooklyn? Will the #BlueJays starters EVER give up a run? Will they boo Tavares on L.I. tonight? Join @torontomike and me",Hebsyman
3688,2019-04-06 22:26:54+00:00,New York,1114731246553268225,Can you tell what the GREAT HORNED OWL was feeding her here OWLETS??? @BirdQueens #GreatHornedOwl #bird_adored #elite_raptors #elite_owls #owl_guru #ethicalowlphotos #birdsofprey #chouetterayee #oiseauxdeproie #oiseaux #wildlifephotography #Raptors – at Hempstead Lake State Park,kikiscamera
3790,2019-04-07 19:57:45+00:00,Los Angeles,1115056098363551744,Incoming osprey after hauling a huge tilapia #bestbirdshots #birdsofinstagram #birdsinflight #osprey #raptors #raptorsofinstagram #tilapia @Sepulveda Basin Wildlife Reserve,J007_

In [40]:
remove_query('bird')

In [41]:
raptors[raptors['Tweet'].str.contains('falcon', case=False)]

,Date,Game Location,ID,Tweet,User
1237,2018-11-23 16:05:17+00:00,New York,1066075235399729153,"#hawk #falcon #NJraptor #raptor #maplewoodnj #natureinthecity @Maplewood, New Jersey",WhereIsJaneMyra
2218,2019-03-07 22:44:20+00:00,Minneapolis,1103863998405992449,#uofm #raptorcenter #eagles #hawks #falcons #vulture #owls #onlyinmn @The Raptor Center,Pauly_ccrider
2254,2019-03-10 15:06:19+00:00,Houston,1104835898443739137,"This is beyond gorgeous, but it somehow reminds me of Raptor, an evil Cobra yuppie tax consultant who took up falconry as a pastime from GI Joe.",manster2099
3849,2019-04-09 12:43:05+00:00,Cleveland,1115671487242035200,Appropriate for the Peregrine falcon exhibit. #raptor – at Lake Erie Nature &amp; Science Center,camorris

In [42]:
remove_query('falcon')

In [43]:
raptors[raptors['Tweet'].str.contains('owl ', case=False)]

,Date,Game Location,ID,Tweet,User
1742,2019-01-13 13:23:21+00:00,Denver,1084516265258074112,A Bald Eagle & Snowy Owl courtesy of the Raptor Education Foundation! #raptors #baldeagle #snowyowl #education #conservation #raptoreducationfoundation @Colorado Convention Center,WXChaser_MJA
1777,2019-01-17 01:52:13+00:00,Charlotte,1085791886437040128,"Saw some pretty cool owls in the Owl Forest section of Carolina Raptor Center like the Barred Owl (photos 2-4), Chaco Owl (photos 5-7) and Barn Owl (photos 8-10). #owlforest #barredowl…",scottchisolm80
1838,2019-01-23 00:27:33+00:00,Charlotte,1087944906545479686,#ThrowbackTuesday to a pair of owls I saw at Carolina Raptor Center last week: Spectacled Owl (slides 1-5) and Great Horned Owl (slides 6-10). #spectacledowl #greathornedowl #owlforest…,scottchisolm80
1885,2019-01-28 17:31:34+00:00,Orlando,1090014548864757761,"Great Horned Owl. I prefer the blue sky over the cloudy background, but I prefer the eyes open over shut. Can't win them all. #owl #owls #owlsofinstagram #owlnest #raptors…",JMBurket
1916,2019-02-02 19:24:45+00:00,Toronto,1091854972122091520,mobile upload pics today #raptors vs #laclippers ticket tomorrow #superbowl weekend #letsgoraptors Marlies vs laval early on #northovereverything @mlsesportsfan24 vicrock221…,mlsesportsfan24
1919,2019-02-03 12:39:12+00:00,Toronto,1092115297266487297,I'm not a fan of the #NFL... I'm a fan of the #NBA... Specifically the #Raptors if you must know. #SUPERBOWL ... I'll come to your party tho The real game time is @3pm #LAClippers vs…,PluckyDGTL
1921,2019-02-03 14:43:09+00:00,Toronto,1092146492327059458,"Raptors at 3, Superbowl at 630. Join us for pizzas, chilli, chicken drums and more. Beer to stay and to go! @Duggan's Brewery",duggansbrewery
1936,2019-02-03 21:25:11+00:00,Toronto,1092247666963243009,A little pre #superbowl #Raptors action. @Toronto Raptors,4pointbball
1939,2019-02-04 04:13:22+00:00,Oklahoma City,1092350388467048448,"Super Bowl Party wines: Analemma 2016 Oak Ridge Vineyard Chardonnay - Columbia Gorge , 88/100; Raptor Ridge 2017 Pinot Noir Rosé Bellevue Cross Vineyard - McMinville , 87/100; Ehlers…",orlowskijp
2490,2019-03-14 21:23:59+00:00,Orlando,1106380492272742400,My first glimpses of 2 Great Horned Owlets. #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest #wildlifepictures #wildlife_shots #wildlife_perfection…,JMBurket
2545,2019-03-16 14:09:37+00:00,Orlando,1106995954694193158,Great Horned Owl keeping watch over two Owlets. #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest #wildlifepictures #wildlife_shots…,JMBurket
2753,2019-03-20 18:03:28+00:00,Orlando,1108504358164094976,Great Horned Owlet yawn. #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest #wildlifepictures #wildlife_shots #wildlife_perfection #nikoncoolpixp900…,JMBurket
2856,2019-03-21 19:51:35+00:00,Orlando,1108893954026729472,"Great Horned Owlet ""dabbing""? #dab #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest #wildlifepictures #wildlife_shots #wildlife_perfection…",JMBurket
2943,2019-03-23 08:06:26+00:00,Orlando,1109441273998524417,Great Horned Owlet out of the nest for the first time. (Lower right of second photo) #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest…,JMBurket
3300,2019-03-29 19:58:10+00:00,Orlando,1111794712036421633,Great Horned Owlet out of the nest. #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest #wildlifepictures #wildlife_shots #wildlife_perfection…,JMBurket
3395,2019-03-31 14:09:18+00:00,Orlando,1112431695385505793,Great Horned Owls. #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest #wildlifepictures #wildlife_shots #wildlife_perfection #nikoncoolpixp900…,JMBurket
3652,2019-04-06 07:16:08+00:00,Orlando,1114502042549202944,Great Horned Owlet at the golden hour. #greathornedowl #owl #only_raptors #elite_raptors #owlet #owlsofinstagram #owls #owlnest #wildlifepictures #wildlife_shots #wildlife_perfection…,JMBurket

In [44]:
remove_query('owl ')

In [45]:
raptors[raptors['Tweet'].str.contains('zoo', case=False)]

,Date,Game Location,ID,Tweet,User
1464,2018-12-13 15:39:14+00:00,Brooklyn,1073316438818111490,The RAPTURE or RAP TRUE. EYE HOVER HIGH VELOCITY RAPTOR coming 4 you. Jetsam and flotsam... Ga-Zoo by the Jetsons... EARTH don't knead you.. mold you.. or shake &amp; bake you. Signed HARRY…,BlakAnkh
1595,2019-01-02 00:01:43+00:00,Portland,1080328258690969600,"The moment we walked in to the zoo, nugget’s first question was “is there a raptor” she was disappointed this being her first time at the zoo and there are no…",bossgaimchng3r
3824,2019-04-08 18:14:04+00:00,Chicago,1115392394395115523,When #MotherNature yells at you that it’s FINALLY decent in the #Midwest you get the #CabInFever raptors and the new little raptor in training to @brookfield_zoo and enjoy it! #FamilyFirst…,RealTeamFight

In [46]:
remove_query('zoo')

In [47]:
raptors[raptors['Tweet'].str.contains('museum', case=False)]

,Date,Game Location,ID,Tweet,User
1559,2018-12-29 00:34:12+00:00,Phoenix,1078886885672529922,This pretty much says it all. Rian does not like raptors. The Arizona Museum of Natural History is great for kids who love dinosaurs. Rian was going crazy naming each one. He has…,ryandavidwinkle
1600,2019-01-02 17:31:16+00:00,San Antonio,1080592387708252161,Well we came to San Antonio to see the spurs...! #sanantonio #travel #raptors @The Briscoe Western Art Museum,joshuakern
2530,2019-03-15 20:39:09+00:00,Boston,1106731596932096000,"ROOOAR!! Big bro of our favorite Christmas raptor. #trex #museumofscience #roar #datenight @Museum of Science, Boston",CraigSEsquire

In [48]:
remove_query('museum')

In [49]:
raptors[raptors['Tweet'].str.contains('aurora', case=False)]

,Date,Game Location,ID,Tweet,User
3215,2019-03-27 20:25:45+00:00,Denver,1111076881292509184,Girls Lax Update: Fruita Monument leads the Raptors 13-10 with about nine minutes left to go on a beautiful spring night at Stutler Bowl. @aurorasports,raptorathletics
3216,2019-03-27 20:52:20+00:00,Denver,1111083567457681408,Girls Lax final: Raptors come up just short tonight 14-12 to Fruita Monument. Great effort @EaglecrestGLax keep grinding !! @aurorasports,raptorathletics
3614,2019-04-05 18:28:45+00:00,Denver,1114308927083155462,Baseball: Raptors score nine runs in the top of the 10th and outlast Overland 18-13 in the completion of yesterday’s suspended game. Way to finish boys !! @aurorasports,raptorathletics
3639,2019-04-05 20:33:02+00:00,Denver,1114340203555184640,Both @Eaglecrest_Lax and @EaglecrestGLax defeat Overland today in Centennial League play. Good work Raptors !! @aurorasports,raptorathletics
3654,2019-04-06 09:03:05+00:00,Denver,1114528957695549441,Raptors in Action Today: Track at the Mullen Invite Baseball hosts Mullen 11:00 AM Boys Lacrosse vs Legend 1:30 PM at Legacy Stadium. Have a great day Raptors !!! @aurorasports,raptorathletics
3663,2019-04-06 12:39:24+00:00,Denver,1114583396683079681,Baseball: Raptors and Mullen scoreless after two innings. @aurorasports,raptorathletics
3797,2019-04-08 01:06:33+00:00,Denver,1115133811849740288,Yo: I have confirmed that Mullen will pursue Eaglecrest's possible use of a pitcher in violation of the pitch count -- say that 5 times fast -- in Saturday's 4-3 Raptors' victory. Stay tuned ... #copreps #Mullenathletics @Presto89 @MullenMustang @mullenalum @aurorasports,neildevlin
3854,2019-04-09 17:35:33+00:00,Denver,1115745089593204737,"Baseball: End of the 1st inning....Raptors 4, Mullen 3. @aurorasports",raptorathletics
3856,2019-04-09 18:03:10+00:00,Denver,1115752038674116613,End of three innings here at Mullen; Raptors lead it 4-3 over Mullen. @aurorasports,raptorathletics
3857,2019-04-09 18:28:23+00:00,Denver,1115758383456575488,"End of four innings...Mullen 10, Raptors 4. @aurorasports",raptorathletics
3861,2019-04-09 18:57:31+00:00,Denver,1115765717075468298,Baseball: Evan Mason with a three-run double to center. Raptors trying to claw their way back now down 12-8 top of the 6th. @aurorasports,raptorathletics
3863,2019-04-09 19:11:46+00:00,Denver,1115769301145915394,Joey Garduno with a two run double.....Raptors now down 12-10 going to the bottom of the 6th. @aurorasports,raptorathletics
3865,2019-04-09 19:25:13+00:00,Denver,1115772688683782144,Baseball: Raptors battle till the end but fall to Mullen 14-10 in Centennial League play this afternoon. Back at it Thursday at home vs Cherokee Trail. @aurorasports,raptorathletics

In [50]:
remove_query('aurora')

In [51]:
raptors[raptors['Tweet'].str.contains('rutgers', case=False)]

,Date,Game Location,ID,Tweet,User
1621,2019-01-05 20:05:34+00:00,New York,1081718382234357761,Game 76 of the season features a @itsjpangs matchup of @scarletraiders &amp; the @RUC_Raptors in @Rutgers_Newark @Golden Dome Athletic Center,BKCowbellGuy
1846,2019-01-23 16:53:37+00:00,Philadelphia,1088193058146082816,ITS GAMEDAY! As we travel to Rutgers-Camden to take on the Scarlet Raptors in a NJAC showdown! Watch us live in the links below! #GoOspreys #d3hoops Watch Live:…,CoachZiggySU
2851,2019-03-21 14:37:35+00:00,Philadelphia,1108814933511335938,"Join us Saturday March 30th from 10AM - 12PM, for a FREE Baseball/Softball Skills & Drills Clinic with the Philadelphia Phillies Jr. RBI and RBI League. @CamdenSchools @CityofCamdenGov @Phillies @RUC_Raptors @Rutgers_Camden – at Athletic and Fitness Center",CHAACamden

In [52]:
remove_query('rutgers')

In [53]:
raptors[raptors['Tweet'].str.contains('space raptor', case=False)]

,Date,Game Location,ID,Tweet,User
1400,2018-12-06 18:09:37+00:00,Orlando,1070817565516083200,"Draught Drop Space Raptor: Hop Ascension . . We did a thing, with our Besties @grasslandsbrew , This cold off the truck Hazey Double IPA will tickle your taste buds on othe edge of…",hourglassbrew
1418,2018-12-09 16:19:00+00:00,Orlando,1071876895103479810,Drinking a Space Raptor Hop Invasion by @hourglassbrew/@grasslandsbrew at @hourglassbrew —,ThemeParkBeer
1555,2018-12-28 16:36:13+00:00,Orlando,1078766596326330368,Not my favorite from here so far. - Drinking a Space Raptor Hop Invasion by @hourglassbrew/@grasslandsbrew at @hourglassbrew —,BigSocial32
1617,2019-01-04 21:00:03+00:00,Orlando,1081369707234672640,Drinking a Space Raptor: Hop Ascension by @hourglassbrew at @hourglassbrew —,CheeseWeasel70
1962,2019-02-07 18:38:04+00:00,Orlando,1093655163867406336,Drinking a Space Raptor: Hop Ascension by @grasslandsbrew/@hourglassbrew at @hourglassbrew —,thephilcollier

In [54]:
remove_query('space raptor')

In [55]:
raptors[raptors['Tweet'].str.contains('paint', case=False)]

,Date,Game Location,ID,Tweet,User
802,2019-03-22 19:12:59+00:00,Toronto,1109246627372584961,Thunder have no answer for Pascal Siakam in the paint,Gedi
879,2018-10-17 21:00:48+00:00,Washington D.C.,1052741253048070144,Another successful Paint Nite! Here are some of our Van Gogh Raptors and their paintings #PaintNite #RaptorNation #Fall2018 @Montgomery College,stusenatetpss
1562,2018-12-29 08:48:46+00:00,Toronto,1079011346820284416,"#Repost drinksbygrace with get_repost ・・・ Check out this super cool painting of our newest @raptors cocktail, the Kawhian Punch, by drinksbygrace . . . “Finally picking my paint brush…",PaiToronto
1747,2019-01-13 16:07:36+00:00,Washington D.C.,1084557598479867913,"nolimittb scores in the paint, but @sergeibaka_7 drains s 3-pointer to put @raptors up 139-138 w/13.9 seconds left in double OT. #wizraptors @washinformer @Capital One Arena",jabariwill
2000,2019-02-10 17:07:22+00:00,Brooklyn,1094719501382443008,"Sunday, February 17, we paint #Fortnite !12 tix left for our fortnite paint party! Choose between Cuddle or Raptor! #kidspaintparty #kidshavingfun…",lourdesgamez3
2046,2019-02-15 14:52:52+00:00,New York,1096497590286266368,"This Sunday, February 17, we paint #Fortnite! 3 tix left for our fortnite paint party! Link in Bio Choose between Cuddle or Raptor! #kidspaintparty…",lourdesgamez3
2055,2019-02-18 12:37:21+00:00,Washington D.C.,1097550651436027905,League of legends raptors costume. This costume was rough. With barely finishing and 4 am painting. My friends really came out with a force to help and I can't thank everyone enough. I…,UnseenDeath
2056,2019-02-18 14:55:04+00:00,Milwaukee,1097585310316224513,Thought for Presidents day it is Appropriate to post this artistic rendition of the American Eagle the symbol of our country. #eagle #americaneagle #presidentsday #USA #painting #raptors…,imagesbylemke
2657,2019-03-18 18:58:34+00:00,Brooklyn,1107793449451954176,Robinson got the Raptors scared to come in the paint,Sheglar_GD
3665,2019-04-06 13:32:08+00:00,Washington D.C.,1114596667976822785,"@montgomerycoll Rockville Open House today with my colleagues from WD&amp;CE, Elementary Ed., and the MC ECE Club face painting and Raptor Tattoos!",sprunedah

In [56]:
remove_query('paint')

In [57]:
raptors.sort_values('Date', inplace=True)
raptors = raptors.reset_index(drop=True)

C:\Users\mitch\Anaconda3\envs\neuralnetworks\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [58]:
raptors

,Date,Game Location,ID,Tweet,User
0,2018-10-09 21:53:14+00:00,Philadelphia,1049855345592557569,She like a bear claw/ She Like Kawhi Leonard/ She tryna lock a nigga right down but imma spin her (OFF THE TOP FREESTYLE) #uproarchallenge #YOUMIDASWELL #offthetop #Freestyle #rap…,Youmidaswell
1,2018-10-10 07:48:14+00:00,Toronto,1050005082748702722,"I’m a Kawhi fan! Just like him, when I laugh, I laugh hard! @Toronto, Ontario",sivedahk
2,2018-10-10 09:35:30+00:00,Toronto,1050032078052503552,Let’s goooo . . #tangerine #scotiabankarena #acc #basketball #raptors #corporate #rally @Scotiabank Arena,AlexHPLai
3,2018-10-10 09:42:30+00:00,Toronto,1050033837592535040,Excited to get onto the court! . . #tangerine #scotiabankarena #acc #raptors #basketball #corproate #rally #goodtimes #nba @Scotiabank Arena,AlexHPLai
4,2018-10-10 13:25:37+00:00,Toronto,1050089985922220032,"@fyinktattoos has tatted Drake, Justin Bieber, the Toronto Raptors...and now this knucklehead. #inktober #inktober2018 #tattoo #tattoos #mannyfacestattoo #fyink mannyfacestattoo #basquiat…",Dannysmithxx
...,...,...,...,...,...
3575,2019-04-10 17:42:48+00:00,Toronto,1116109300177489922,You Wanna Play The Raptors First Round?,Miss_Angel_Baby
3576,2019-04-10 17:50:33+00:00,Orlando,1116111251887804417,"So who do we want to face?!? Bucks, Raptors, or 76ers?! #puremagic",Gosurf911
3577,2019-04-10 18:07:30+00:00,Los Angeles,1116115516744065024,Jerry West isn’t coming BACK. TOO Busy building the tracks to KAWHI for the CLIPP JOINT..,spurharry
3578,2019-04-10 18:13:49+00:00,Toronto,1116117106439925765,"He coached Kyle, FVV, Siakam (who’s a totally different player), OG, Norm and ibaka (being used properly unlike how Casey used him). Raptors are a totally different squad Plus Casey notoriously got outcoached. I can’t wait to sweep them",Arysaf
3579,2019-04-10 18:52:37+00:00,Oklahoma City,1116126871547207680,The Raptors would be a pretty nice fit for him....,_Poochie66

In [59]:
raptors.to_csv('data/tweets/raptors/raptors_cleaned_tweets.csv')