In [9]:
import pandas as pd
import numpy as np

# Getting total season schedule (all teams) with attendance numbers

In [12]:
df1 = pd.read_csv('../data/attendance/2018-2019/october_2018_nba_attendance.csv')
df2 = pd.read_csv('../data/attendance/2018-2019/november_2018_nba_attendance.csv')
df3 = pd.read_csv('../data/attendance/2018-2019/december_2018_nba_attendance.csv')
df4 = pd.read_csv('../data/attendance/2018-2019/january_2019_nba_attendance.csv')
df5 = pd.read_csv('../data/attendance/2018-2019/february_2019_nba_attendance.csv')
df6 = pd.read_csv('../data/attendance/2018-2019/march_2019_nba_attendance.csv')
df7 = pd.read_csv('../data/attendance/2018-2019/april_2019_nba_attendance.csv')

df_list = [df1,df2,df3,df4,df5,df6,df7]

In [13]:
season_2018 = pd.DataFrame()

In [14]:
#combine all seasons into one df
for i in df_list:
    season_2018 = season_2018.append(i, ignore_index=True)

In [15]:
season_2018

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 16, 2018",8:00p,Philadelphia 76ers,87,Boston Celtics,105,Box Score,NaN,18624,NaN
1,"Tue, Oct 16, 2018",10:30p,Oklahoma City Thunder,100,Golden State Warriors,108,Box Score,NaN,19596,NaN
2,"Wed, Oct 17, 2018",7:00p,Milwaukee Bucks,113,Charlotte Hornets,112,Box Score,NaN,17889,NaN
3,"Wed, Oct 17, 2018",7:00p,Brooklyn Nets,100,Detroit Pistons,103,Box Score,NaN,20332,NaN
4,"Wed, Oct 17, 2018",7:00p,Memphis Grizzlies,83,Indiana Pacers,111,Box Score,NaN,17923,NaN
...,...,...,...,...,...,...,...,...,...,...
1274,"Sun, Apr 28, 2019",3:30p,Houston Rockets,100,Golden State Warriors,104,Box Score,NaN,19596,NaN
1275,"Mon, Apr 29, 2019",8:00p,Philadelphia 76ers,94,Toronto Raptors,89,Box Score,NaN,19800,NaN
1276,"Mon, Apr 29, 2019",10:30p,Portland Trail Blazers,113,Denver Nuggets,121,Box Score,NaN,19520,NaN
1277,"Tue, Apr 30, 2019",8:00p,Boston Celtics,102,Milwaukee Bucks,123,Box Score,NaN,17536,NaN
1278,"Tue, Apr 30, 2019",10:30p,Houston Rockets,109,Golden State Warriors,115,Box Score,NaN,19596,NaN

In [7]:
# remove playoff games
season_2018.iloc[1230:, :]
season_2018 = season_2018.drop(season_2018.index[1230:])

In [8]:
season_2018.head()

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 16, 2018",8:00p,Philadelphia 76ers,87,Boston Celtics,105,Box Score,NaN,18624,NaN
1,"Tue, Oct 16, 2018",10:30p,Oklahoma City Thunder,100,Golden State Warriors,108,Box Score,NaN,19596,NaN
2,"Wed, Oct 17, 2018",7:00p,Milwaukee Bucks,113,Charlotte Hornets,112,Box Score,NaN,17889,NaN
3,"Wed, Oct 17, 2018",7:00p,Brooklyn Nets,100,Detroit Pistons,103,Box Score,NaN,20332,NaN
4,"Wed, Oct 17, 2018",7:00p,Memphis Grizzlies,83,Indiana Pacers,111,Box Score,NaN,17923,NaN

In [9]:
capacity = pd.read_csv('../data/attendance/arena_capacity.csv')

In [10]:
capacity.head()

,Image,Arena,Location,Team(s),Capacity,Opened,Ref(s)
0,NaN,American Airlines Arena,"Miami, Florida",Miami Heat,19600,1999,[1][2]
1,NaN,American Airlines Center,"Dallas, Texas",Dallas Mavericks,19200,2001,[1][3]
2,NaN,Amway Center,"Orlando, Florida",Orlando Magic,18846,2010,[1][4]
3,NaN,AT&T Center,"San Antonio, Texas",San Antonio Spurs,18418,2002,[1][5]
4,NaN,Bankers Life Fieldhouse,"Indianapolis, Indiana",Indiana Pacers,17923,1999,[1][6]

In [11]:
capacity_dict = dict(zip(capacity['Team(s)'], capacity['Capacity']))
capacity_dict

{'Miami Heat': 19600,
 'Dallas Mavericks': 19200,
 'Orlando Magic': 18846,
 'San Antonio Spurs': 18418,
 'Indiana Pacers': 17923,
 'Brooklyn Nets': 17732,
 'Washington Wizards': 20356,
 'Golden State Warriors': 18064,
 'Oklahoma City Thunder': 18203,
 'Memphis Grizzlies': 17794,
 'Milwaukee Bucks': 17500,
 'Sacramento Kings': 17583,
 'Detroit Pistons': 20332,
 'New York Knicks': 19812,
 'Portland Trail Blazers': 19441,
 'Denver Nuggets': 19520,
 'Cleveland Cavaliers': 19432,
 'Toronto Raptors': 19800,
 'New Orleans Pelicans': 16867,
 'Charlotte Hornets': 19077,
 'Los Angeles Clippers': 19068,
 'Los Angeles Lakers': 18997,
 'Atlanta Hawks': 18118,
 'Phoenix Suns': 18055,
 'Minnesota Timberwolves': 18978,
 'Boston Celtics': 18624,
 'Houston Rockets': 18055,
 'Chicago Bulls': 20917,
 'Utah Jazz': 18306,
 'Philadelphia 76ers': 20478}

In [12]:
# add arena capacity to season 2018 df
season_2018['Capacity']= season_2018['Home/Neutral'].map(capacity_dict)
season_2018

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes,Capacity
0,"Tue, Oct 16, 2018",8:00p,Philadelphia 76ers,87,Boston Celtics,105,Box Score,NaN,18624,NaN,18624
1,"Tue, Oct 16, 2018",10:30p,Oklahoma City Thunder,100,Golden State Warriors,108,Box Score,NaN,19596,NaN,18064
2,"Wed, Oct 17, 2018",7:00p,Milwaukee Bucks,113,Charlotte Hornets,112,Box Score,NaN,17889,NaN,19077
3,"Wed, Oct 17, 2018",7:00p,Brooklyn Nets,100,Detroit Pistons,103,Box Score,NaN,20332,NaN,20332
4,"Wed, Oct 17, 2018",7:00p,Memphis Grizzlies,83,Indiana Pacers,111,Box Score,NaN,17923,NaN,17923
...,...,...,...,...,...,...,...,...,...,...,...
1225,"Wed, Apr 10, 2019",8:00p,Chicago Bulls,109,Philadelphia 76ers,125,Box Score,NaN,20197,NaN,20478
1226,"Wed, Apr 10, 2019",8:00p,Dallas Mavericks,94,San Antonio Spurs,105,Box Score,NaN,18629,NaN,18418
1227,"Wed, Apr 10, 2019",10:30p,Minnesota Timberwolves,95,Denver Nuggets,99,Box Score,NaN,16332,NaN,19520
1228,"Wed, Apr 10, 2019",10:30p,Utah Jazz,137,Los Angeles Clippers,143,Box Score,OT,17655,NaN,19068
1229,"Wed, Apr 10, 2019",10:30p,Sacramento Kings,131,Portland Trail Blazers,136,Box Score,NaN,19814,NaN,19441

In [13]:
season_2018.to_csv('../data/attendance/2018-2019/2018_2019_attendance.csv')

# team specific game attendance

In [14]:
raptors_att = pd.DataFrame()

In [15]:
def attendance_combiner(season_att, team_string, team_att):
    away_mask = season_att['Visitor/Neutral'] == team_string
    home_mask = season_att['Home/Neutral'] == team_string
    team_att = team_att.append(season_att[home_mask])
    team_att = team_att.append(season_att[away_mask])
    team_att['Date'] = pd.to_datetime(team_att['Date'])
    team_att['Attend.'] = pd.to_numeric(team_att['Attend.'])
    team_att['Capacity'] = pd.to_numeric(team_att['Capacity'])
    team_att['Attendance Ratio'] = (team_att['Attend.'] / team_att['Capacity'])
    return(team_att)

In [16]:
#isolate raptors season information from season 2018 df
raptors_att = attendance_combiner(season_2018, 'Toronto Raptors', raptors_att)
raptors_att = raptors_att.sort_values(by='Date')
raptors_att = raptors_att.reset_index()
raptors_att

,index,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes,Capacity,Attendance Ratio
0,7,2018-10-17,7:30p,Cleveland Cavaliers,104,Toronto Raptors,116,Box Score,NaN,19915,NaN,19800,1.005808
1,21,2018-10-19,8:00p,Boston Celtics,101,Toronto Raptors,113,Box Score,NaN,19800,NaN,19800,1.000000
2,26,2018-10-20,7:00p,Toronto Raptors,117,Washington Wizards,113,Box Score,NaN,16185,NaN,20356,0.795097
3,40,2018-10-22,7:30p,Charlotte Hornets,106,Toronto Raptors,127,Box Score,NaN,19800,NaN,19800,1.000000
4,54,2018-10-24,7:30p,Minnesota Timberwolves,105,Toronto Raptors,112,Box Score,NaN,19800,NaN,19800,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,1155,2019-04-01,7:30p,Orlando Magic,109,Toronto Raptors,121,Box Score,NaN,19800,NaN,19800,1.000000
78,1168,2019-04-03,7:30p,Toronto Raptors,115,Brooklyn Nets,105,Box Score,NaN,17732,NaN,17732,1.000000
79,1179,2019-04-05,7:00p,Toronto Raptors,111,Charlotte Hornets,113,Box Score,NaN,18684,NaN,19077,0.979399
80,1194,2019-04-07,12:00p,Miami Heat,109,Toronto Raptors,117,Box Score,OT,19800,NaN,19800,1.000000
81,1213,2019-04-09,8:00p,Toronto Raptors,120,Minnesota Timberwolves,100,Box Score,NaN,16119,NaN,18978,0.849352

In [17]:
one_mask = raptors_att['Attendance Ratio'] > 1

In [18]:
raptors_att['Attendance Ratio'] = raptors_att['Attendance Ratio'].where(~one_mask, 1)

In [19]:
raptors_att

,index,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes,Capacity,Attendance Ratio
0,7,2018-10-17,7:30p,Cleveland Cavaliers,104,Toronto Raptors,116,Box Score,NaN,19915,NaN,19800,1.000000
1,21,2018-10-19,8:00p,Boston Celtics,101,Toronto Raptors,113,Box Score,NaN,19800,NaN,19800,1.000000
2,26,2018-10-20,7:00p,Toronto Raptors,117,Washington Wizards,113,Box Score,NaN,16185,NaN,20356,0.795097
3,40,2018-10-22,7:30p,Charlotte Hornets,106,Toronto Raptors,127,Box Score,NaN,19800,NaN,19800,1.000000
4,54,2018-10-24,7:30p,Minnesota Timberwolves,105,Toronto Raptors,112,Box Score,NaN,19800,NaN,19800,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,1155,2019-04-01,7:30p,Orlando Magic,109,Toronto Raptors,121,Box Score,NaN,19800,NaN,19800,1.000000
78,1168,2019-04-03,7:30p,Toronto Raptors,115,Brooklyn Nets,105,Box Score,NaN,17732,NaN,17732,1.000000
79,1179,2019-04-05,7:00p,Toronto Raptors,111,Charlotte Hornets,113,Box Score,NaN,18684,NaN,19077,0.979399
80,1194,2019-04-07,12:00p,Miami Heat,109,Toronto Raptors,117,Box Score,OT,19800,NaN,19800,1.000000
81,1213,2019-04-09,8:00p,Toronto Raptors,120,Minnesota Timberwolves,100,Box Score,NaN,16119,NaN,18978,0.849352

In [20]:
raptors_att.to_csv('../data/attendance/teams/raptors_2018_2019_attendance.csv')

In [21]:
#do rest for other five teams
lakers_att = pd.DataFrame()
bucks_att = pd.DataFrame()
rockets_att = pd.DataFrame()
warriors_att = pd.DataFrame()
knicks_att = pd.DataFrame()

In [22]:
lakers_att = attendance_combiner(season_2018, 'Los Angeles Lakers', lakers_att)
lakers_att = lakers_att.sort_values(by='Date')
lakers_att = lakers_att.reset_index()
mask = lakers_att['Attendance Ratio'] > 1
lakers_att['Attendance Ratio'] = lakers_att['Attendance Ratio'].where(~mask, 1)
lakers_att.to_csv('../data/attendance/teams/lakers_2018_2019_attendance.csv')

In [23]:
bucks_att = attendance_combiner(season_2018, 'Milwaukee Bucks', bucks_att)
bucks_att = bucks_att.sort_values(by='Date')
bucks_att = bucks_att.reset_index()
mask = bucks_att['Attendance Ratio'] > 1
bucks_att['Attendance Ratio'] = bucks_att['Attendance Ratio'].where(~mask, 1)
bucks_att.to_csv('../data/attendance/teams/bucks_2018_2019_attendance.csv')

In [24]:
rockets_att = attendance_combiner(season_2018, 'Houston Rockets', rockets_att)
rockets_att = rockets_att.sort_values(by='Date')
rockets_att = rockets_att.reset_index()
mask = rockets_att['Attendance Ratio'] > 1
rockets_att['Attendance Ratio'] = rockets_att['Attendance Ratio'].where(~mask, 1)
rockets_att.to_csv('../data/attendance/teams/rockets_2018_2019_attendance.csv')

In [25]:
warriors_att = attendance_combiner(season_2018, 'Golden State Warriors', warriors_att)
warriors_att = warriors_att.sort_values(by='Date')
warriors_att = warriors_att.reset_index()
mask = warriors_att['Attendance Ratio'] > 1
warriors_att['Attendance Ratio'] = warriors_att['Attendance Ratio'].where(~mask, 1)
warriors_att.to_csv('../data/attendance/teams/warriors_2018_2019_attendance.csv')

In [26]:
knicks_att = attendance_combiner(season_2018, 'New York Knicks', knicks_att)
knicks_att = knicks_att.sort_values(by='Date')
knicks_att = knicks_att.reset_index()
mask = knicks_att['Attendance Ratio'] > 1
knicks_att['Attendance Ratio'] = knicks_att['Attendance Ratio'].where(~mask, 1)
knicks_att.to_csv('../data/attendance/teams/knicks_2018_2019_attendance.csv')